### ISSUE TITLE
黑客与画家

### ISSUE THREAD

**Issue by yxiaohui** [ReadingBooktogether/OneBookOneWeek#1]
# 本周任务
阅读《黑客与画家》，任选一章，在12.15之前提交你的note。

# 提交格式

> 
\# 第x章 xxx

 \## 你最强烈的感受（mandatary）

 \## 哪些适用于我们，怎么适用到我们的工作（mandatary）

 \## 重要的概念/人名（mandatary）
  \- 概念/人名：
  \- 印象：
  \- 例子：
  \- 出处：

 \## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
  \- 反常识：
  \- 印象：
  \- 例子：
  \- 出处：

**Comment by chilichicken** [comment]
test

**Comment by chilichicken** [comment]
test

**Comment by stone-monkey** [comment]
# 第10章 编程语言的解析
## 你的笔记（optional）
10. 编程语言的解析
机器语言
解释机器语言就是让机器做按照指令执行任务
高级语言
用编译器解释成机器/汇编语言
开放源码
Linux和Windows的对比,开发源码就像一片经受同行评议的论文
语言的战争
"语言不重要,重要的是你对问题是否有正确的理解" -- 这当然是一派胡言
抽象性
编程语言可以变得很抽象,完全脱离硬件,但也有可能走错了方向
安全带还是手铐
静态语言?动态语言?
面向对象编程
某些语言允许你使用这种风格,另一种则是强迫."我"觉得后一类不可取. 
文艺复兴
编程语言的文艺复兴, 很多语言产生. 如果我们所有人都使用同一种编程语言,反而可能是坏事.
## 你最强烈的感受（mandatary）
作者明确的支出语言之间有很大的差别,语言也会发展.而且语言的不同使用者时间的确也存在鄙视链. :)
## 哪些适用于我们，怎么适用到我们的工作（mandatary）
开放源码,的确是一种提高软件质量的方式.不过对于大公司,涉及到安全,开放源码可能不容易做到.
## 重要的概念/人名（mandatary）
- 概念/人名：作者认为语言的差别非常大,并不是经常听到的"语言不重要,重要的是你对问题是否有正确的理解" 
- 例子：早期的Perl语言和Perl语言也是差距很大的
- 出处：语言的战争
## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：
- 例子：
- 出处：
# 第11章 一百年后的编程语言
## 你的笔记（optional）
11. 一百年后的编程语言
"我"预言java也会如此, 如尼安德特人一样,进化之路已经走到尽头. 当然要看标准. --> 作者的猜测
编程语言的进化和生物学进化相似,但也是有区别的.
任何一种编程语言都可以分成两大组成部分: 基本运算符的集合(扮演公理角色), 除运算符以外的其他部分(这个部分可以用 基本运算符表达出来).
那些内核最小,最干净的编程语言才会存在于进化的主干上.
软件发展历史已经50年,但是编程语言的进化其实非常缓慢
一百年后的计算机速度一定很快,但摩尔定律最终将不成立(18个月增长一倍)
不仅编程语言, 一种普遍的历史趋势: 随着技术的发展, 每一代人都在做上一代觉得浪费的事情. --> 长途电话,邮寄包裹
应该将语言的语义与语言的实现予以分离. -->语义上不需要同时存在字符串和列表,单单列表就够了. 而在实现上做好编译器的优化
一般年后的程序员最需要的编程语言就是可以让你毫不费力地写出程序第一版的编程语言,哪怕它效率低下的可怜,但是他们想要的是容易上手的编程语言.
面向对象编程将来不会消亡. --> "我"觉得,除了特定领域, 这种编程方法并没有对优秀程序员带来好处,但对大公司有不可抗拒的力量.
一百年后,并行计算不会很流行.
新语言更多的以开源项目的形式出现, 另一种趋势是新语言的设计者本身就是需要使用他们的应用软件作者.
两个观点: 1)一百年后的编程语言在理论上今天就能设计出来; 2) 如果今真能设计出这样的一种语言, 很可能现在就适合编程并能产生更好的结果.
## 你最强烈的感受（mandatary）
虽然作者的很多观点和猜测未必真的会变成现实,但是作者的思考方式让人很钦佩和学习的.各种预言都是基于当前的现实基础,做出合理的逻辑推理. 我们需要学习这种思考方式. 并且作者的一些想法并没有人云亦云. 如作者不认为面向对象编程对优秀程序员带来好处.
## 哪些适用于我们，怎么适用到我们的工作（mandatary）
作者提到了静态语言和动态语言. 更倾向于动态语言,而且有理有据的推测动态语言是一种发展方向,或许我们需要思考我们应该如何开放的去拥抱未来的技术发展, 而不局限于我们之前的知识背景.
## 重要的概念/人名（mandatary）
- 概念/人名：未来的计算机速度一定很快.
- 例子：都是猜测
- 出处：
## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：1. 一百年后,并行计算不会很流行. 2. 面向对象编程并没有对优秀程序员带来好处.
- 例子：都是猜测
- 出处：

**Comment by spicychicken** [comment]
# 第6章 如何创造财富

## 你的笔记（optional）
任何致富 => 创业(or加入创业公司) => 创业公司的实质: 解决某个技术难题的小公司

1. 为什么创业公司必须是小公司?
2. 为什么当创业公司不断变大时, 不开避免的失去创新力?
3. 为什么创业公司往往选择在新技术领域创业?

为什么创业:
创业过程的实质: 以高(或者极限)强度工作几年, 以期换取高额的回报. (可以理解为: 压缩几十年的工作,回报到几年)
承受较大的压力通常为你带来额外的回报. 

创业 => 通过创造有价值的东西而致富 => 做出别人需要的东西.

金钱不等于财富  => 财富是我们需要的东西, 金钱只是财富的一种简便的表达方式. 金钱是财富交换中的一种中介, 通过它方便的获得自己想要的东西.
你所拥有的财富是 => 人们愿意用金钱和你交换的东西.

为什么选择创业公司?
在大公司工作, 最大的困扰是无法准确测量每个员工的贡献. 只要你一般性的工作, 就能得到意料之中的薪水.
可测量性和可放大性: 
你的贡献必须可以被测量
你做出的决定能够产生巨大的效应(血汗工厂工人, 电影中的主角, CEO), 测量可放大性的一个方式是: 看失败的可能性. 
收入和风险是对称的, 有巨大的获利可能, 就必然存在巨大的失败可能.
(对应到IT工作中, 就是成为某个攻克难题的小团体的一部分)
团体小,工作贡献容易被测量. 团体大, 每个人的贡献就越接近于整体的平均值. 小团体=>可测量性
技术=>做事的方式, 它的经济价值取决于多少人使用这种新方式. 技术是钓鱼的鱼竿, 而不是鱼.
大多数通过创造财富而发财的人都是通过开发新技术而实现的.
小团体不收官僚主义和繁琐管理制度的拖累, 能够采用非常规的方法实现技术的突破. (大公司也能开发出新技术, 只是速度较慢).
选择公司要解决什么问题应该是问题的难度为指引. 实际操作中, 故意选择那些很困难的技术问题.(可以迫使竞争对手跟我们一起走入沼泽地).
创业的付出与回报总体上是成比例的, 但具体到个体, 是不成比例的. 

出售创业公司: 
促成买方掏钱的最好办法:不是让买家看到获利的可能, 而是让他们感到失去机会的恐惧. 对买家来说, 最强的收购动机是竞争对手可能收购你.次强的动机是现在不收购, 你的高速成长将使未来的收购耗资巨大.
归根结底的因素是用户数量, 开办创业公司不是为了解决问题, 而是为了解决用户关心的问题.


## 你最强烈的感受（mandatary）
金钱不等于财富, 你所拥有的财富是人们愿意用金钱和你交换的东西.
创造人们需要的东西, 就是创造财富.
开办创业公司不是为了解决问题, 而是为了解决用户关心的问题.

## 哪些适用于我们，怎么适用到我们的工作（mandatary）
创造有价值的东西,做出别人需要的东西.

## 重要的概念/人名（mandatary）
- 概念/人名：财富是我们需要的东西, 金钱只是财富的一种简便的表达方式. 金钱是财富交换中的一种中介, 通过它方便的获得自己想要的东西
- 例子：财富是你需要的东西, 各式各样的物品. 在一个鸟不拉屎的地方, 你需要水, 食物, 药品, 唯独不需要金钱.
- 出处：

## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：
- 例子：
- 出处：

**Comment by inkbottle** [comment]
# 第3章 不能说的话

## 你的笔记（optional）

1. 我们是先贤思维结晶的奴隶，不管我们看起来有多思维自由
2. 流行的不见得是对的，毫无依据的随波逐流十分危险。

有一些话不能说：
1. 社会的排他性
2. 认知的局限性

**如何认识**
### 随大流

不能别人说的话都相信，那样会丧失自己的判断。
不能别人的经验都不借鉴，那样别人的错误你都必须范过一遍你才能得到正确的结论。
这中间需要一种取舍的方式，达到恰到好处的平衡。

### 真话
这里所谓“不能说的话”指的是跟相当一部分人的认知有冲突，但是又的确正确的内容。

### 异端邪说

不移动正确的，但是极富争议性。

### 时空差异

时间不同，社会观念在变化。

### 道貌岸然


### 机制

伽利略只是在宣扬哥白尼的观念，但是前者收到迫害，但是后者却安然无恙。不是观念本身的原因。伽利略正赶上教廷内部反对派上场。

### 为什么这样做

传统的观念对聪明人的束缚力更小。 作为“异端”，不仅在科学领域，在任何有竞争的地方，只要你能看到别人看不到或者不敢看的东西，你就更有优势。

**认识之后**

### 守口如瓶
别说，或者挑选合适的场合。只打值得打的仗。
自由思考比畅所欲言更重要。

这看起来很懦弱，但这不是问题，问题是：不能享受讨论的好处。
更好的回答：我还没想好

实在不能缄口不言的时候，反击的方法：
- 上升到抽象层次
- 使用隐喻

## 你最强烈的感受（mandatary）

- 人们教育孩子的方式，希望并教导孩子以良好的言行和思想，害怕孩子学坏，但是事实上，这与我们生活的环境是相悖的。这到底是为了孩子还是为了自己？将这个假象的世界灌输给小孩子。

- 流行观念和流行服饰的流行方式十分相似。想把自己和普通人区分开来。
- 远距离观察人群，远距离观察自己

## 哪些适用于我们，怎么适用到我们的工作（mandatary）

## 重要的概念/人名（mandatary）
- 概念/人名：失败主义
- 例子：1940年，任何反对丘吉尔的人都被贴上失败主义的标签被清理。
- 出处：


- 概念/人名：守口如瓶，笑脸相迎
- 例子：
- 出处：1638年，弥尔顿访问意大利。

- 概念/人名：如果自己是潮水的一部分，怎么看见潮流的方向呢，只能永远保持怀疑。
- 例子：
- 出处：1638年，弥尔顿访问意大利。

## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：对孩子的教育
- 例子：
- 出处：

- 反常识：更好的回答 - 我还没想好
- 例子：
- 出处：

- 反常识：小时候受到鼓励，不断成长；很少有人鼓励你继续撑场，变成怀疑和地址社会错误潮流的人。
- 例子：
- 出处：

**Comment by inkbottle** [comment]
# 第5章 另一条路

## 你的笔记（optional）

### 一个例子：ASP（应用服务供应商）的诞生
从另一个视角看出趋势

### 下一个潮流
一般用户： 桌面电脑 -- 互联网软件

### 用户的胜利
“你的电脑”正在过时，用户需要的是“你的数据”
软件在云端解决了软件分发和升级的问题，同时还有bug修正。
互联网应用能同时被多人使用。

### 代码之城
互联网软件 & 桌面程序：
建筑与城市
互联网软件可以使用多种语言开发

### 软件的发布
桌面程序的分发完全是一种灾难。patch更是如此。
互联网软件是连续性渐变的。本质上没有版本的说法。比如淘宝。


### 软件bug
互联网软件的优势，能再现大部分bug。不必像桌面软件一样，苦苦猜测发生了什么。
互联网软件每时每刻都在被使用，bug很快会浮出水面。
解决新的bug比历史遗留bug容易：
- 熟悉代码
- 早一点发现不容易行程复合式bug： 楼梯很滑+扶手松了。
- 软件经常发布，每次幅度很小。产生复合bug的几率更小。

### 客服支持
互联网软件的开发和客服离用户更近。
新功能： 大公司的做法是不立刻实现新功能，而是做计划。


### 逆向的人月神话
人数越少，开发效率也将指数级增长。

### 关注用户
- 软件应该做到用户认为它可以做到的事情。
- 你能得到用户数据，所以不再需要依赖基准测试。
- 软件效率足够高，有足够的用户，每个用户的分担的硬件成本接近免费。
- 关注用户由于优化程序和指导设计。

### 金钱问题
互联网软件的销售额每个季度不是从零开始，而是持续的现金流。
没有盗版，多一个用户使用你的软件，你的市场影响力就在扩大
放弃对服务器的直接控制，就放弃了互联网软件的大部分优势，分销软件不是好的销售模式。


### 创业公司
加班与压力，用户的压力在变小，程序要压力在变大。

### 勉强够用的网页

### 尝试一下

## 你最强烈的感受（mandatary）

## 哪些适用于我们，怎么适用到我们的工作（mandatary）

## 重要的概念/人名（mandatary）
- 概念/人名：
- 例子：
- 出处：

## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：
- 例子：
- 出处：

**Comment by yxiaohui** [comment]
# 第4章 良好的坏习惯

## 人名卡
- 人名：理查德· 费曼（Richard Phillips Feynman，1918年5月11日－1988年2月15日）
- 印象： 美国理论物理学家，量子动力学家，纳米技术之父。
- 例子： 由费曼提出的完善的费曼图、费曼规则和重整化计算方法是研究量子电力学的重要工具。出版自传《别闹了，费曼先生》
- 出处： 维基百科

## 人名卡
- 人名： 迈克 罗宾（Micheal Robin）


## 术语卡
- 术语：曼哈顿工程（Manhattan Project）
- 印象： 第二次世界大战期间研发与制造原子弹的一项大型军事工程，由美国以及给予支援的英国与加拿大执行，该计划于1942年到1946年间直属于美国陆军工程兵团的莱斯利· 格罗夫斯将军领导，工程原名”代用材料项目发展“（Development of Substitute Materials），后改为曼哈顿工程。
- 例子:  1945年7月16号，美国的第一颗原子弹在新墨西哥州的沙漠试爆成功。8月6日，美国向广岛投放名为”小男孩“的原子弹；8月9日，向长崎投放”胖子“。
- 出处： 维基百科

## 术语卡
- 人名： 美国精神
- 印象： 自由独立精神、奋斗精神、富而善的精神品质、公平精神、宽容精神
- 例子： 美国《独立宣言》
- 出处： http://m.bwchinese.com/article/1071753.html

## 反常识
- 反常识：黑客的最大的优点是不服管教
- 印象： 通常我们认为服从管教的乖孩子才是最好的，但是这类听话的好孩子反而没有创造力。创造力是思维天马行空的释放，不被刻板的条条框框束缚，超越常规，在行为不服从权威，特立独行，不刻意讨好别人。
- 例子： 顶级黑客

## 反常识
- 反常识：知识产权对技术发展的阻碍，研究和改进当前的技术，才能构想下一代技术
- 印象： 只是产权保证技术的发展

## 反常识
- 反常识：下一代技术大都是在大公司外部产生的
- 印象： 大公司拥有充足的资本，人员和其它资源，下一代技术应该在大公司产生。
- 例子： 个人电脑没有产生在IBM，而是由两个不相干的长头发青年（乔布斯，沃兹尼亚克）在旧金山的一间车库里发明的。
- 出处： 黑客与画家，P54

## 任意卡
- 美国是个移民国家，冒险和创新精神早已植根于美国人的基因里。

**Comment by ZLimin** [comment]
**第1章 书呆子为什么不受欢迎**
书呆子不受欢迎的真正原因是他们的注意力都放在读书和观察世界上，而不是一些无关紧要的事情上，书呆子一直在追求如何使自己更加聪明，而不是在想如何变得受欢迎。

但书呆子离开学校到了社会上时，却能受到友好的对待，不会像小孩那样以欺负书呆子来突显自己的’优越’; 真实的世界中做每件事都能产生实际意义上的效果，得到正确的答案是非常重要的。书呆子更早的开始思考真正世界中所需要的东西。
- 人名：比尔盖茨
- 例子：不善交际，但现在创造了巨大的财富

所以我们不应该固步自封，应该思考的更加全面，向前看。

**- 第2章 黑客与画家**

 黑客与画家是有共同之处的，他们都是创作者;但本质上他们都不是在做研究。

## 哪些适用于我们，怎么适用到我们的工作（mandatary）
 

- 大多数人认为黑客/程序员就是用软件去实现某个功能，而不是去设计软件，而且很少一部分程序员懂

   得如何真正设计软件，所以你要有很大的竞争优势，就得懂得如何软件设计

例子：微软，Apple

- 要做自己喜欢的事情，有一分“白天工作”，即有一份为生计赚钱的工作，一份为了爱好的工作。如果你不爱好你的工作，你就不能把它做的很优秀。

- 画家与黑客是一样的，如果要把画画好，就要动手去画，而程序员一样，如果要设计了优秀的软件，就要学习如何编程。

- 画家如果要做出优秀的作品，就是要从优秀的作品中学习。黑客也一样，可以通过观看优秀程序学会编程，不是只看程序的运行结果，而是看源代码，所以程序员要多看一些优秀的源代码来提高自己的技能。

- 画家完成一幅画是从一张草图到细节逐步完成的，程序员也应该这样，不能期望一开始就得到完美的设计，应该在编程过程中逐步完善，最终得到完美结果。

- 坚持一丝不苟，就能得到优秀的成果。优秀的软件也要求追求完美。最基础的就是代码的缩进，变量名的命名。。。

- 黑客与画家一样，工作起来有一定的心理周期，在你感兴趣的时候，你会有很大的热情去工作，当过一段时间，你可能就对此毫无兴趣。所以要做出优秀的成果，在你有很大兴趣时把主要的和困难的部分完成，在你厌倦的时候再做比较容易的工作，比如在编程中，可以把bug留到最后去解决。

- 从绘画中不仅可以学到如果管理自己工作，还可以学到如何与他人一起工作。完成一个软件需要与他人一起合作，但也不要合作过度。正确的合作模式是把项目分成严格定义的模块，每一个模块由一个人明确负责。模块与模块之间的接口进行精心设计，最好有清晰的文档说明

- 软件是为人使用的，所以黑客与画家一样要时刻考虑用户的实际需求，程序员要学会换位思考，不仅是为了你的用户，也是为了你的读者，要使你或者别人能够读懂你的代码。

## 你最强烈的感受（mandatary）

- 把自己的精力放在有意义的事情上，提升自己的思维，放长眼光。

- 培养你的乐趣爱好，只有你对编程有很大的爱好，才能写出好的程序，设计出优秀的软件。

- 持续学习

**Comment by Lemon312** [comment]
第6章 如何创造财富

如果你想致富，最好的办法就是创业。
为啥是创业？
创业是高强度的工作。
可以专注的工作，排除干扰及复杂程序流程。
获得大财富需要极好的运气。

大饼谬论：财富总额是固定不变的。
实际上财富是不停的净增长。
修一辆车，修好了财富增长。

工作是什么
工作就是加入一个组织，开始做自己正常情况下没兴趣做的事情

大公司最大的困扰就是无法准确测量每个员工的贡献。大多数情况下只是瞎猜。
小规模=可测量
创业的测量=用户数量

你最强烈的感受（mandatary）
工作就是开始做自己正常情况下没兴趣做的事情。

哪些适用于我们，怎么适用到我们的工作（mandatary）
扩大产品的用户数量。
怎么使用？不知道

重要的概念/人名（mandatary）
- 概念/人名：NOthing
- 例子：NOthing
- 出处：NOthing
哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：大饼谬论
- 例子：x%的人口占有了y%的财富
- 出处：黑客与画家 P120

第7章 关注贫富分化

财富的老爹模式
一个孩子给的多，其他孩子就会叫不公平
但不能总靠父母，由于每个人的创造财富能力和欲望强烈程度都不一样，所以每个人创造财富数量也不一样
每个人的技能不同，导致收入不同，这才是贫富分化的主要原因。
财富应当是满足他人的需求的创造活动。

偷窃
不管是战争还是政治斗争，本质上都是偷窃
高额的税负也是偷窃。

技术的发展加大了贫富差距。
如果参观yahoo，intel，cisco的办公室大家都穿差不多，同样的小隔间，但是每个人的银行余额却又很大差别
如果社会保持进步，同时收入差距不扩大，只能是创造财富的人没有获得报酬。唯一的可能就是兴趣。

你最强烈的感受（mandatary）
要提高自己的技术
哪些适用于我们，怎么适用到我们的工作（mandatary）
提高技能，来创造更多的财富。
重要的概念/人名（mandatary）
- 概念/人名：Jobs
- 例子：CEO的收入不足以体现他所创造的财富。拯救了apple公司，扭转危机并决策了下一代产品
- 出处：P140
哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：NOthing
- 例子：NOthing
- 出处：NOthing

**Comment by Ironman-Jason** [comment]
# 第九章 设计者的品味
## 你最强烈的感受（mandatary）
品味放映了美是一种客观存在，设计者的品味直接影响设计的美感和设计的价值。

好设计是简单的设计。（装饰品往往掩盖了核心和结构的苍白无力）
好设计是永不过时的设计。（风潮）
好设计是解决主要问题的设计。（煤气灶按钮）
好设计是启发性的设计。（蒙娜丽莎的微笑）
好设计通常是有点趣味性的设计。（幽默代表对厄运的一笑了之）
好设计是艰苦的设计。（攀登高峰需要扔掉一切不必要的装备）
好设计是看似容易的设计。（台上十分钟，台下十年功。）
好设计是对称的设计。（对称是简洁的一种表现，大自然也充满了对称。）
好设计是模仿大自然的设计。（模仿不是剽窃，模仿也诞生出美的设计。）
好设计是一种再设计。（敢于站在肩膀之上，敢于扔掉原型。）
好设计是能够复制的设计。（复制好的设计以期进入原创和超脱自我的境界。）
好设计常常是奇特的设计。（黑鸟超音速侦察机）
好设计是成批出现的。（人才的成批涌现，让有天赋的人聚在一起，共同解决某个难题。）
好设计常常是大胆的设计。（敢于猜想，大逆不道？轻信权威？）

## 哪些适用于我们，怎么适用到我们的工作（mandatary）
好设计是简单的设计。
好设计是一种再设计。

## 重要的概念/人名（mandatary）
- 概念/人名：
- 例子：
- 出处：
## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：轻信权威
- 例子：我们所有人都受到凯利-约翰逊的影响，狂热地相信外观优美的飞机一定会飞得漂亮。
- 出处：本-里奇《臭鼬计划》

**Comment by windypu** [comment]
# 第4章 良好的坏习惯

## 你最强烈的感受（mandatary）
一个人们拥有言论自由和行动自由的社会，往往最有可能采纳最优方案，而不是采纳最有权势的人提出的方案。

## 哪些适用于我们，怎么适用到我们的工作（mandatary）
最新的版权法设置了前所未有的障碍，禁止外部人员了解专有技术的内部细节，从而也就禁止了外部人员从这个途径构想，如果我们不可以研究当前技术，不能思考如何改进它，那我们怎么才能开发新技术呢。

##  重要的概念/人名（mandatary
- 概念/人名：史蒂夫 乔布斯 史蒂夫 沃兹尼亚克
- 例子：真正的电脑不是诞生于IBM的实验室，而是由两个完全不相干的年轻人在旧金山的一间车库里完成的
- 出处：黑客与画家

## - 概念/人名：肯 汤普森  丹尼斯 里奇
- 例子：计算机工业的几大巨头聚集在一起合作研发官方版的下一代操作系统Multics，但是另外两个人肯 汤普森  和 丹尼斯 里奇觉得Multics 过于复杂就另起炉灶写出了一个自己的操作系统UNIX
- 出处：黑客与画家

## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：不服从管教
- 例子：版权和专利这样的制度 威胁到完成工作所必须要的思想自由，阻碍计算机工业的进步
- 出处：黑客与画家

**Comment by windypu** [comment]
# 第8章 防止垃圾邮件的一种方法
## 你最强烈的感受（mandatary）
以为通过修改关键字为谐音字就可以实现发布一些敏感词汇的文章，但其实并不一定能实现。
大多数黑客的直觉是写出一个能够识别垃圾邮件某种特征的的软件，比如搜索邮件中的点击字样就能过滤出79.9%的垃圾邮件，但却有1.2%的误判。这种方法要把识别精度提高变得很困难。
## 哪些适用于我们，怎么适用到我们的工作（mandatary）
 使用统计学过滤器实现过滤垃圾邮件
通过两个很大的正常邮件组和垃圾邮件组，的到两张散列表，分别有键（标识符）值（标识符出现的次数）组成。
创建第三个散列表由标识符和标识符是垃圾邮件的概率这样的键值对组成。
![default](https://cloud.githubusercontent.com/assets/19277676/21305615/ae81439a-c607-11e6-942e-fbcdb0ffa2c2.png)
![default](https://cloud.githubusercontent.com/assets/19277676/21305667/f1011fe2-c607-11e6-9b57-6522b50ea419.png)

当收到新邮件，程序会自动扫描，读出邮件中所有实意标识，再找出其中15个最醒目标识（概率偏离中性值0.5最远的标识），用他们判断整封邮件是垃圾邮件的概率
![default](https://cloud.githubusercontent.com/assets/19277676/21304914/5bb6dc50-c603-11e6-89ac-6c507e15f89a.png)
这个公式计算出来的值大于0.9，就可以把这封邮件设置为垃圾邮件
理想的情况下，每个收信人都有自己单独的概率分布表，用户自己创建一个清单，包含一些自己经常收到的邮件的关键词，这样收到的邮件中包含这些词就自动通过过滤，并且更新散列表，这样是的垃圾邮件的发送者不能根据基本概率分布表做出调整

## 重要的概念/人名（mandatary

    概念/人名：数学家 Norbert Wiener
    例子：如果你与奴隶比赛，你也会变成奴隶
    出处：黑客与画家

## 哪些观点跟你原来的理解不一样（反常识）（mandatary）

    反常识：无
    例子：无
    出处：无

**Comment by zhonghuaz** [comment]
# **第12章 拒绝平庸 & 第13章 书呆子的复仇**
## 你的笔记（optional）
- 大公司可以互相模仿，创业公司不行：

![image](https://cloud.githubusercontent.com/assets/24557583/21375652/eb4b2bca-c769-11e6-8d2e-e46bcf28ac34.png)

- 编程语言之间能力是有差异的，使用过更高级的语言才知道哪些语言处于更下层。大多数认为编程语言都差不多，所以通常会选用一些流行的业界标准语言，比如Java,当然对于公司来说，也更容易招到开发人员。

![image](https://cloud.githubusercontent.com/assets/24557583/21376000/8ca18486-c76c-11e6-9080-406f600272b6.png)

- **技术的变化速度通常是很快的，但是编程语言不一样，与其说它是技术，不如说它是程序员的思考模式。**
- 对业界最佳实践的解读：

![image](https://cloud.githubusercontent.com/assets/24557583/21376077/27722664-c76d-11e6-94c2-bc0188e4dcdc.png)
![image](https://cloud.githubusercontent.com/assets/24557583/21376118/688e4b3c-c76d-11e6-98d3-86748d2d15b0.png)

## 你最强烈的感受（mandatary）
- 在时代大潮中不随波逐流，坚持己见很难，只有坚持做下来并且做的比其他人更好

## 哪些适用于我们，怎么适用到我们的工作（mandatary）
-在自己有选择权的情况下，选择自己认为最强大的编程语言，不随波逐流，不盲目追求业界最佳实践。快且强大才是技术取胜的要点。

## 重要的概念/人名（mandatary）
- 概念/人名：**LISP 语言，约翰·麦卡锡，λ演算**
- 印象：**编程语言在朝着数学的方向发展，而不是向着语言的方向**
- 例子： **Java8,以及.Net都在开始支持Lamada表达式。**
- 出处：

## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：**（我自己的常识：编程语言之间都差不多）编程语言之间差异很大**
- 印象：**作者的观点是，语言之间差异很大，Lisp是最强大的编程语言。**
- 例子：
**使用Lisp的公司：
Amazon
eBay
Facebook
Heroku
Walmart**
- 出处：http://clojure.org/community/companies

**Comment by Oogway1983** [comment]
**# 第1章 为什么书呆子不受欢迎**
**## 你最强烈的感受（mandatary）**
了解了美国青少年（11-17岁）的一些思维模式。
-发现一个除父母外的新世界（同龄人的世界），并更在乎这个新世界里的感受。
-大多数青少年更在乎自己是否受欢迎（注重自己的外貌，穿着之类的，影响因素包括 相貌、魅力、运动能力等），少数人开始观察世界，在乎自己能不能更聪明一点（聪明并不能增加在青少年中受欢迎的程度，也不减少。）
-同伴的意见成为他们判别事物的标注。
-希望融入到群体中（为了结成群体，常常需要一起干一件事：一起欺负某个“书呆子”，一起抽烟 等等。。）
-成人的世界更在乎你所做的是否产生实际意义，所以智力是重要因素。孩子的世界，他们所做的并不能看到实际意义（至少在当时是这样），无聊对于他们来说可能是一个常态（空虚）。
-孩子们的等级是凭空创造出来的（即在没有任何严肃标准的前提下，产生排名的情况。--倒退至人缘比赛）
-学校的教育有很多不足之处
-在这场人缘的比赛中输家，包括"书呆子"和"怪人"
-青少年的叛逆，并不是体内激素分泌失调。。


**## 哪些适用于我们，怎么适用到我们的工作（mandatary）**


**第4章 良好的坏习惯**
**## 你最强烈的感受（mandatary）**
-黑客
-不服管教 （思维天马行空）
-热衷于解决无法解决的问题 （专研精神）
-知识产权 与 黑客的思想自由 （学习最新的技术才能更进一步）
-黑客的所作所为完全出于兴趣 （兴趣）
现在程序员的世界越来越倾向于开源了。
**## 哪些适用于我们，怎么适用到我们的工作（mandatary）**
