### ISSUE TITLE
改变 问题形成和解决的原则

### ISSUE THREAD

**Issue by yxiaohui** [ReadingBooktogether/OneBookOneWeek#2]
# 本周任务
《改变 问题形成和解决的原则》
任选一章， 12.15之前提交你的输出

## 内容简介：
在我们的日常生活中，合平常理及遵从逻辑的思维方式．确实是一种解决之道，但有时中规中矩的做法反而导致 失败，而那些看似不合逻辑和非理性的行动，却出乎意料地使问题得以改善。这种矛盾悖论的现象．正是本书所要探讨的主题。

## 提交格式：
尽量多做输出
每一个概念或者人名，请分别拷贝一份模板填写。
\# 第x章 xxx
\## 你最强烈的感受（mandatary）
\## 哪些适用于我们，怎么适用到我们的工作（mandatary）
\## 重要的概念/人名（mandatary）
\- 概念/人名：
\- 印象：
\- 例子：
\- 出处：
\## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
\- 反常识：
\- 印象：
\- 例子：
\- 出处：

## 概念：
 - 概念： 心流（Flow）
 - 印象： 别名化境（Zone），亦有人翻译成神驰状态，是一种将个人精神力完全投注在某种活动上的感觉，心流产生时同时会有高度的兴奋与充实感。希斯赞特米哈伊认为，是心流发生的活动有一下特征
  1. 我们倾向去从事的活动
  2. 我们会专注一致的活动
  3. 有清楚目标的活动
  4. 有立即回馈的活动
  5. 我们对这个活动有主控感—挑战与技能之间达到平衡
  6. 在从事活动是我们的忧虑感消失
  7. 主管时间改变—例如可以从事很长的时间而不感觉时间的流逝
-	例子： 做一件自己喜欢的手工。
-	出处： [维基百科](https://zh.wikipedia.org/wiki/%E5%BF%83%E6%B5%81%E7%90%86%E8%AB%96)

**Comment by stone-monkey** [comment]
# 第3章 原地踏步, 或者当解决之道变成问题
## 你最强烈的感受（mandatary）
- 本章标题就是本章的主要观点. 当解决之道变成问题. 我们在解决问题的时候, 因为会使用不同的解决方案, 以致会导致不同的结果. 当解决的办法并不适合的时候, 反而解决办法成了比问题更严重的问题.
## 哪些适用于我们，怎么适用到我们的工作（mandatary）
- 虽然有些问题的严重性可能维持在某一个程度, 但许多问题如果未经处理或者处理不当, 非但维持不了多久, 而且容易趋于恶化 -- 尤其当错误的解决方案一再被使用.
- 我们在对解决方案的选取的时候, 尽量先取得足够的信息, 再从各种备选的解决方案中选取最合适,且不会造成更坏后果的方案.

## 重要的概念/人名（mandatary）
- 概念/人名：负反馈现象
- 印象：负反馈调节：使生态系统达到或保持平衡或稳态，结果是抑制和减弱最初发生变化的那种成分的变化。反馈又称回馈，是控制论的基本概念，指将系统的输出返回到输入端并以某种方式改变输入，进而影响系统功能的过程。反馈可分为负反馈和正反馈。前者使输出起到与输入相反的作用，使系统输出与系统目标的误差减小，系统趋于稳定；后者使输出起到与输入相似的作用，使系统偏差不断增大，使系统振荡，可以放大控制作用。对负反馈的研究是控制论的核心问题。另外有电流负反馈的理论。
- 例子：负反馈在电子电路中应用非常广泛。在放大电路中，利用负反馈可以稳定静态工作点和放大倍数，可以减小非线性失真、扩展频带，还可以改变放大器的输入阻抗和输出抗阻。
- 出处：百度百科

## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：代沟
- 印象：本以为代沟是存在于最近的几代人,原来早已存在数千年
- 例子：在一块据推算至少有三千年历史的巴比伦泥板上写着: 今日的年轻人真是坏到了极点, 他们邪恶,不信神而懒惰. 他们根本比不上从前的年轻人, 他们根本不能保护我们的文化.
- 出处：古巴比伦泥板.

**Comment by windypu** [comment]
# 第9章 改变的实践
## 你最强烈的感受（mandatary）
如果一个问题非常复杂和深层次的问题时，设定具体可达成的目标。
## 哪些适用于我们，怎么适用到我们的工作（mandatary）
解决问题的步骤：
1）以具体的词语清楚的界定问题
2）探究截止目前为止已经企图应用过的解决方案
3）对想要达成的具体改变有个清晰的定义
4）形成和执行一个能够产生这一改变的计划

失败的原因：
不切现实，或不恰当的目标
选择介入的方法的性质，如果我们给予的指导没有产生任何正向的改变那么我们的指导就是错误的
未能用“语言”对当事人说明方法，并使他愿意愿意接受和实行这个方法

## 重要的概念/人名（mandatary）
- 概念/人名：罗森塔尔效应 rosenthal effect
- 印象：人们把像这种由他人（特别是像老师和家长这样的“权威他人”）的期望和热爱，而使人们的行为发生与期望趋于一致的变化的情况，称之为“罗森塔尔效应”。
- 例子：问题假设者若对人类问题报持冰山假设，他所设立的目标可能会创造一种罗森塔尔效应
- 出处：改变：问题形成和解决原则

## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：经由悖论尔产生的第二序改变
- 印象：
- 例子：失眠，强迫自己保持清醒
- 出处：改变：问题形成和解决原则

**Comment by Ironman-Jason** [comment]
# 第6章 悖论
## 你最强烈的感受（mandatary）
    这是篇好文章！ 尽量避免自己陷入悖论的泥潭，尽管这是无法避免的，所以让反思成为一种好的习惯。
## 哪些适用于我们，怎么适用到我们的工作（mandatary）
    Self motivation is so important. (自我激励非常重要。) 让别人去“激励”你自己，这本身也是悖论的一个形式。

## 重要的概念/人名（mandatary）
- 概念/人名：
    所有的克里特岛人都是说谎者。--------埃庇米尼德斯（Epimenides， 公元前6世纪，克里特岛人）， 他创造过一个克里特悖论，他说：“所有克里特人都是骗子。”这是很明显的矛盾命题，因为他自己就是克里特岛人。
 说谎者悖论：https://zh.wikipedia.org/wiki/%E8%AA%AA%E8%AC%8A%E8%80%85%E6%82%96%E8%AB%96
  在哲学和逻辑学中，古典的说谎者悖论是指一个说谎者声称自己正在说谎：例如，声称：“我正在说谎”或者“我所说的皆为假”。如果他确实在说谎，那么他所说的就是真的，但如果他所说的就是真的，那么他就是在说谎。在“这个语句正在说谎”的悖论中，为了强化悖论，使悖论更经得起严格的逻辑分析，“说谎”的概念往往被“真假”的概念所取代，仅仅保留“说谎者”这一名称来指涉关于古典二值逻辑会推导出矛盾的悖论。

    克里特：https://zh.wikipedia.org/wiki/%E5%85%8B%E9%87%8C%E7%89%B9
 克里特岛（希腊语：Κρήτη，Kríti；古希腊语：Κρήτη，Krḗtē），位于地中海北部，是希腊的第一大岛，总面积8,300平方公里。行政上属于克里特大区。
   克里特是最古老的欧洲文明“米诺斯文明”的中心（也就是说，这里文明早于欧洲和希腊，而不是来自欧洲和希腊）。这种文明的起源几乎不为人所知（与小亚细亚地区的古老文明有关但与欧洲无关）。该文明留下的文字记录并不多，而且它们使用的是一种称作“线性文字A”的人们至今无法解读的文字。
    埃庇米尼德斯：https://zh.wikipedia.org/wiki/%E5%9F%83%E5%BA%87%E7%B1%B3%E5%B0%BC%E5%BE%97%E6%96%AF
- 很好的例子：
    详见分享材料

**Comment by inkbottle** [comment]
# 第5章 乌托邦症候群

## 你最强烈的感受（mandatary）

试图以乌托邦来改变现况，会使得问题陷入胶着，甚至越来越糟。

当问题搞砸时：
- introjective. 认为是自己能力不够，自责，但是不认为是目标本身是不可达到的。这些困境有可能使得人“退出社会”。
- 认为目标需要更多努力，陷入拖拉，并不责备自己。用这样的心态和说辞让自己在未能抵达目标，到处游荡这样的结果面前让自己不至于自责或者情绪陷入崩溃。

- projective. 认为自己的观念站在真理这边，宣扬并企图说服别人。不认同的人就认为是坏人，要施与惩戒。


## 哪些适用于我们，怎么适用到我们的工作（mandatary）

如果未能找到问题的解答，那多半是做了错误的假设为前提，而不是尚未发现正确的方法。
不能把具体问题的具体改变，寄托在一个极其遥远的可能实现的目标的达成上。

一味的追求不可能的事情，会使得原本可能的事情变得不可能。

## 重要的概念/人名（mandatary）
- 概念/人名：乌托邦
- 印象：
- 例子：
- 出处：1516年，托马斯·莫尔的小说


- 概念/人名：人生有两个悲剧，一个是心愿无法达成；另一个是终于达成所愿。
- 印象：
- 例子：
- 出处：萧伯纳


## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识： 对于乌托邦症候群，需要改变的是前提，而不是找出方法。
- 印象：
- 例子：
- 出处：

**Comment by Lemon312** [comment]
第4章 可怕的简化

你最强烈的感受（mandatary）
好复杂，说实话看不懂。
本文好像在强调，不能把复杂的问题简单化的归一为单一因素：
如环境问题是由于人的贪欲，战争问题是由于人的贪欲。

有些人粗糙地简化了复杂的系统。若要让自己的观点站得住脚，只有拒绝去看事物复杂性。

哪些适用于我们，怎么适用到我们的工作（mandatary）

重要的概念/人名（mandatary）

概念/人名：莱恩
印象：神经病 （明明看到真相却连自己都无法承认）
例子：他们正在玩一场游戏，他们正在玩不是游戏的游戏。如果我说我看到他们在玩游戏，我便犯了规，他们就会惩罚我。我必须玩这场游戏，一场没看到我在玩游戏的游戏。
出处：
哪些观点跟你原来的理解不一样（反常识）（mandatary）

反常识：
印象：
例子：
出处：

**Comment by zhonghuaz** [comment]
# 第7章 第二序改变 （Second Order Change）

## 你最强烈的感受（mandatary）
庸人自扰：有些问题本身造成的困扰远不及解决这个问题所采取的方法带来的困扰。 也就是说有些问题总也解决不了是因为你一直应对这个问题的解决方案有问题。
跳出圈外来，不纠结，拔高一个层次、换一个角度想问题，完成第二序改变，会豁然开朗。
## 哪些适用于我们，怎么适用到我们的工作（mandatary）
平时遇到难题时候，不妨跳出来想一想，不要停留在第一序改变上，第二序改变会让问题不再成为问题。
## 重要的概念/人名（mandatary）
- 概念/人名：第二序改变
- 印象：1、一种改变发生在某系统之内，而系统本身维持不变；另一改变发生时，则改变了系统本身。前者叫第一序改变，后者叫第二序改变
2、某种情况下，新问题的产生，纯粹是因为改变既存问题的方式的错误，如果人们只知道造成第一序改变，其结果不是使应该解决的问题变的更为恶化，就是解决方案本身实际上变成了问题。 简单概况一下处理不当的三种方式： a. 企图以否定问题存在的方式来解决问题：应当有所行动，却无行动; b. 企图改变不是无法改变或根本就不存在的困难：不应当采用行动，却采取了行动； c. 在错误的逻辑层次上采取了行动：（1）更高一级的逻辑才能改变时试图用第一序改变某种状况，或（2）第一序改变足以解决困难时，却试图促成第二序改变
- 例子：
- 出处：
## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：
- 印象：
- 例子：
- 出处：

**Comment by spicychicken** [comment]
# 第一章 理论的观点
## 你最强烈的感受
打破常规.
## 哪些适用于我们，怎么适用到我们的工作
打破常规
## 重要的概念/人名
- 概念/人名：群论: 
a.群是具有某一共同特征的成员所组成.(群的成员的本质不在群论的考虑范围, 群的成员可以是任何概念, 物体, 数字, 事件等)
 (组合是指群的某一可能的内在状态转换成另一内在状态的一种变化. 群的任何成员的组合, 其结果本身仍是该群的成员.
b.成员可以以不同的顺序来组合, 而组合的结果仍然相同. (e.g: 从一个平面的某一点出发, 向东南西北移动, 其最终还是会回到出发点).
c.每一个群皆包含一个恒等成员, 任何一位其他成员与该恒等成员组合, 其结果仍为该成员本身.
d.在任一符合群概念的系统中, 每一成员皆有相对或相反成员, 任一成员跟它的相反成员组合, 结果为恒等成员. 
- 印象：
- 例子：自然数, 钟表
- 出处：

- 概念/人名：逻辑类型理论: 整体叫做种类, 组成分子叫做成员.  (凡涉及某集合的全部成员者, 必然不是该集合的一员).
- 印象：
- 例子：人类和人类的个体.
- 出处：

- 概念/人名：第一序改变: 改变发生在系统之内, 系统维持本身不变.
- 印象：
- 例子：群论涉及的. 手动挡汽车油门
- 出处：

- 概念/人名：第二序改变: 改变发生时, 改变了系统本身.
- 印象：
- 例子：逻辑类型理论, 手动挡汽车换挡
- 出处：

## 哪些观点跟你原来的理解不一样(反常识)
- 反常识：
- 印象：
- 例子：
- 出处：

**Comment by Oogway1983** [comment]
第2章  实践的观点
你最强烈的感受（mandatary）
把数学的群论运用到社会问题的解决当中来，很有创意，但是太过抽象，不好理解。
哪些适用于我们，怎么适用到我们的工作（mandatary）
当你陷入进退两难的境地时，需要换个视角去审视，找到产生第二序改变的改变。
重要的概念/人名（mandatary）
第一序改变：改变发生在系统之内, 系统维持本身不变.
第二序改变：改变发生时, 改变了系统本身.

**Comment by ZLimin** [comment]
# 第八章 重新框定的艺术
## 概念：重新框定

- 重新框定是指将人们赖以理解或经验某种情境的概念与情绪的假设或观点，改变成另一组同样也能“符合事实”（甚至更好）的设定，经过这一转换，该情境对人们的意义已全然改变。

- 重新框定的机制并未涉及情绪的变化，而是当情境并未变化时，人们赋予该情境的意义已经改变了，以至于结果也不一样了，但具体的事实仍然维持不变。

- 我们赋予一件事物一定的意义和价值，决定了它的各类属性。但当我们一旦赋予事物的意义和价值后，那么就很难用另一种属性或者意义去看待它。所以同一件事情是好是好，主要是看我们主观上如何看待它。

- 所以重新框定强调将新的种类成员引入我们的概念中，并使我们能用新观点去观察事物。也就是说从另一面对看待事物。

- 成功的重新框定是要将当事人的观点，期望，理由及假设都纳入考虑这内，需要有一个能让问题改变的框架。
- 重新框定不是让我们注意到什么，不是产生什么洞察，而是让我们看待事情不一样了。

## 你最强烈的感受
不是事情本身令我们困扰，而是我们所持的关于事情的意见在困扰我们
没有什么事情是好或是坏，只不过人们的思考让事情是好或是坏。

例如在我们日常生活中，遇到一件事，如果刚开始就把认为它很困难，那么在你心里就觉得自己完成不了; 但如果你认为没有解决不了的事情，那么你就不会害怕它，从而也能够解决它。

## 哪些适用于我们，怎么适用到我们的工作（mandatary）
当你遇到问题并陷入无助状态时，找不到解决办法时，试着跳出当前思维，从另一方面重新思考，可能会重新找到解决方法。

**Comment by yxiaohui** [comment]
# 第七章 第二序改变

## 概念卡
- 概念：迷思（mythologlies）
- 印象： 迷思是一个可能真实或者不真实的故事，通常比较古老。一些迷思也许源于真实事件，但经过人们的讲述和重新讲述，它们的一部分可能已经发生了改变。和阿道夫‧希特勒是同学。
- 例子： 神话故事
- 出处： https://zh.wikipedia.org/wiki/%E8%BF%B7%E6%80%9D

## 人名卡
- 人名： 路德维希‧約瑟夫‧約翰‧维根斯坦（Ludwig Josef Johann Wittgenstein，1889年4月26日－1951年4月29日）
- 印象： 生于奥地利，后入英国国籍。20世纪最有影响力的哲学家之一，其研究领域主要在数学哲学、精神哲学和语言哲学等方面。
- 例子： 1921年出版《逻辑哲学论》

## 反常识
- 反常识： 行动直接作用于困难本身，而不是讨论困难为什么发生
- 印象： 我们总是想找出为什么产生问题的原因，而这对问题的解决并没有太大帮助。
- 例子： 第7章小女孩在母亲准备离开是很沮丧，母亲的离开是小女孩沮丧的直接原因，而母亲解决的办法就是陪着小女孩，这仅仅阻断了产生沮丧的原因，但是问题本身没有解决，并且阻断了问题解决的可能性。而当母亲因事不能陪伴的时候，小女孩哭了一阵之后就安静了下来，隔天母亲送她上学离开的时候也没有哭闹，母亲的因事离开作用于问题的本身，是问题发生了改变，问题得以解决。
- 出处： 改变 第7章

## 可以应用到工作中的
- 跳出情景，重新框定参与者都能接受的情景
- 当解决方案无效或者是情况变得更糟时，这个方案可能就是无法解决问题的关键
- 第二序改变解决方法是处理此时此地的情景，重要的问题是什么（what），而不是为什么（why）
