### ISSUE TITLE
程序员的思维修炼

### ISSUE THREAD

**Issue by yxiaohui** [ReadingBooktogether/OneBookOneWeek#3]
# 本周任务
[《程序员的思维修炼》](https://book.douban.com/subject/5372651/)
任选一章，12.18之前提交

## 内容简介

本书解释了为什么软件开发是一种精神活动，思考如何解决问题，并就开发人员如何能更好地开发软件进行了评论。书中不仅给出了一些理论上的答案，同时提供了大量实践技术和窍门。本书供各层次软件开发人员阅读。

##  作者简介
Andy Hunt 敏捷开发权威人士，敏捷宣言首倡者之一，著名IT图书出版公司Pragmatic Programmers创始人。除本书外，他还与人合著有多本获奖图书，深受读者欢迎，包括《高效程序员的45个习惯——敏捷开发修炼之道》、《程序员修炼之道——从小工到专家》等。

## 提交格式：
尽量多做输出
每一个概念或者人名，请分别拷贝一份模板填写。
\# 第x章 xxx
\## 你最强烈的感受（mandatary）

\## 哪些适用于我们，怎么适用到我们的工作（mandatary）

\## 好的句子

\## 重要的概念（mandatary）
\- 概念：概念或者术语的名字
\- 印象：对概念或者术语的解释
\- 例子：对概念或者术语理解有帮助的例子
\- 出处：

\## 重要的人名（mandatary）
\- 人名：名字（英文名，方便查阅）
\- 印象：这个人的国籍，身份和其他重要信息
\- 例子：重要的观点，成就和著作
\- 出处：

\## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
\- 反常识：
\- 印象：
\- 例子：
\- 出处：

## 概念：
 - 概念： 心流（Flow）
 - 印象： 别名化境（Zone），亦有人翻译成神驰状态，是一种将个人精神力完全投注在某种活动上的感觉，心流产生时同时会有高度的兴奋与充实感。希斯赞特米哈伊认为，是心流发生的活动有一下特征
  1. 我们倾向去从事的活动
  2. 我们会专注一致的活动
  3. 有清楚目标的活动
  4. 有立即回馈的活动
  5. 我们对这个活动有主控感—挑战与技能之间达到平衡
  6. 在从事活动是我们的忧虑感消失
  7. 主管时间改变—例如可以从事很长的时间而不感觉时间的流逝
-	例子： 做一件自己喜欢的手工。
-	出处： [维基百科](https://zh.wikipedia.org/wiki/%E5%BF%83%E6%B5%81%E7%90%86%E8%AB%96)

**Comment by stone-monkey** [comment]
# 第3章 认识你的大脑
## 笔记
- 大脑的配置是双CPU, 单主机总线设计. 两个CPU提供了L型和R型处理模式.
- 1号CPU主要负责线性, 逻辑思维和语言处理. 线性模式, L型. 让你细致工作实现目标.
- 2号CPU更像神奇的数字信号处理器. 富模式, R型. 对直觉, 问题解决和创造性非常重要.
- 刚睡醒尝试描述梦?梦是在R型下产生的, 尝试描述会造成L/R的总线争用.
- R型不能直接控制
- R型会针对努力解决过的事情,建立指针/索引.
- 捕捉所有想法,以从中获益更多. (使用钢笔,笔记本,PDA,录音笔.......)
- 每个人都有好点子
- 生物学家Roger W. Sperry --> 脑裂, 之后提出的左脑思维和右脑思维. Betty Edwards提出了L/R思维模式.
- L型思维的特点: 语言能力, 分析能力, 符号能力, 抽象能力, 时间能力, 推理能力, 数字能力, 逻辑能力, 线性思维能力.
- R型思维: 非语言--> 综合, 具体, 分析, 非理性--> 空间性, 直觉, 全面
- R型中直觉, 是成为专家所需要的.
- L型是必须的, 但仅有它是不够的.

## 你最强烈的感受（mandatary）
- 在丰富的环境中,每个人可以通过不断的学习, 观察和交互, 新脑细胞会不断的产生. 而且大脑是可塑的, 也能够不断的学习, 变成更聪明, 取得更多技能......

## 哪些适用于我们，怎么适用到我们的工作（mandatary）
- 大脑分为L/R型. 程序员更多的是L型, 线性完成工作.
- 不过我们也可以多培养R型的训练, 培养综合, 直觉, 全面的能力. 毕竟设计胜于功能.

## 好的句子
- 每个人都有好点子
- R型中直觉, 是成为专家所需要的.
- L型是必须的, 但仅有它是不够的.

## 重要的概念（mandatary）
- 概念：裂脑(Split-brain)
- 印象：是指连接大脑左右脑的胼胝体受损到一定的程度后时的症状，医疗上的胼胝体横切术亦会造成此种症状。
- 例子：当一个影像只投射在裂脑患者的左视觉区，他们并没有能力说出他们看见了什么。这可分成三阶段解释：
  1. 左视觉区的影像只会传递到右脑；
  2. 大部分人的语音控制中心在左脑；
  3. 裂脑患者目前的左右脑交流是被抑止的。
因此，患者没有办法说出被传递到右脑的影像是什么。若语音控制中心在右脑的人，则将影像投射在右视觉区，也会产生一样的结果。
- 出处：维基百科

- 概念：破窗理论(Broken Window Theory)
- 印象：是犯罪学的一个理论，由詹姆士·威尔逊及乔治·凯林（George L. Kelling）提出，刊载于《The Atlantic Monthly》1982年3月版的一篇题为《Broken Windows》的文章上[1]，论及环境中的不良现象如果被放任存在，就会诱使人们仿效，甚至变本加厉。
以一幢有少许破窗的建筑为例，如果那些窗不被修理好，可能将会有破坏者破坏更多的窗户。最终他们甚至会闯入建筑内，如果发现无人居住，也许就在那里占领、定居或者纵火。又或想像一条人行道有些许纸屑，如果无人清理，不久后就会有更多垃圾，最终人们会视为理所当然地将垃圾顺手丢弃在地上。因此破窗理论强调着力打击轻微罪行有助减少更严重罪案，应该以零容忍的态度面对罪案。
- 例子：
- 出处：维基百科

- 概念：神经可塑性
- 印象：神经可塑性是指的由于经验原因引起的大脑的结构改变。神经可塑性是近期的发现，过去的科学家往往认为在婴儿关键期后，大脑结构往往不发生变化。 大脑有神经元细胞和神经胶质细胞构成，这些细胞互相连接，通过加强或削弱这些连接，大脑的结构可以发生改变。
- 例子：盲人在通过训练以后, 能通过舌头"看"东西. 通过16*16的像素输出到盲人舌头, 能够在停车场自如驾驶.
- 出处：本书

## 重要的人名（mandatary）
- 人名：罗杰·斯佩里(Roger Wolcott Sperry)
- 印象：在十九世纪，由于对受过同个脑部伤害的人们进行研究，开始有人对“语言中心”通常在左半脑产生怀疑。例如，有个人观察到人们在左脑的特定的两个地方产生病变会损失讲话的能力。罗杰·斯佩里和他的同事们最早开始进行这类的研究。在他早期的动物研究中，斯佩里留下了许多有价值的发现，在这些研究中发现到有关于大脑两半球功能特化，他在三十年后的1981年得到诺贝尔生理学或医学奖。在裂脑患者的帮助下，他开始做一些历史上没有做过的实验，揭露了左右脑的存在。
- 例子：
- 出处：维基百科

## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：记忆必须刷新
- 印象：大脑中没有静态RAM,只有动态RAM.这种RAM需要不断的刷新. 如果这种刷新不存在来, 那么记忆也就消失了. 
- 例子：一种位于突触的称为PKM zeta的酶相当于微型记忆引擎,通过改变突触节点的结构的某些方面保持记忆运行.
- 出处：本书

- 反常识：禁锢扼杀脑细胞
- 印象：以前以为脑细胞从出身就定了,只能死亡,不再新生.但是伊丽莎白.高尔德(Elizabeth Gould)证明了成年时期, 在一个丰富的环境中, 里面充满了学习, 观察和交互式无, 新脑细胞会大量产生.
- 例子：
- 出处：本书

**Comment by Oogway1983** [comment]
# 第5章 调试你的大脑
## 你最强烈的感受（mandatary）
暂无

## 哪些适用于我们，怎么适用到我们的工作（mandatary）
认知偏见
时代影响（写C出道的，避免带着偏见去学习JAVA）
个性倾向 （了解自己的性格倾向）
硬件故障 （人的大脑里存在一些适应原始社会的自然反应机制，所以有时人本能的一些反应并不一定都正确）

## 好的句子
我们不是理智的生物。
你“”认为是这样“”并不代表这是正确的。
这意味着在项目末尾时你会达到智力高峰，而在项目开始时则是最无知的。因此，你想尽快做决定吗？不。
你无法改变别人。

## 重要的概念（mandatary）
- 概念：认知偏见
- 印象：思想上的bug，会影响决策过程、记忆、直觉、理性思维等。
      包括：思维定势（惯性）
                基本归因错误：我们倾向于把别人的行为归因于他们的个性，而不去考虑行为发生时的情景。请记住行为经常是对情景的相应而不是基本的个性使然。
                自私的偏见：
                需要定论：我们对疑问和不确定性感到不舒服--这种感觉如此强烈（有时过多的讨论细节）
                认可上的偏见：每一个人都根据自己的成见和喜好原则来选择相应的事实。
                曝光效应：我们往往对因为非常熟悉某些事物而对它有所偏爱。这包括不再好用甚至会出错的工具、技术或者方法。
                霍桑效应：人们在知道自己正被审视时，往往会改变自己的行为。（这方面心理学已经有更好的认知）
                虚假记忆：大脑很容易把想象的事件和真实的记忆混淆。
                符号约简谬论：其它章的内容
                名词谬论：同上

## 重要的概念（mandatary）
- 概念：柏拉圖圈（Platonic fold）
- 印象：是爆炸的外緣，在此處，柏拉圖式的想法和雜亂的現實接觸，而且，在此處，你所知道的和你以為知道的之間的缺口，大到可能引發危險。黑天鵝事件就在此處產生。
- 例子：讓我們認為自己懂得比實際還多的，就是柏拉圖式思想
- 出处：黑天鵝效應（The Black Swan）

**Comment by inkbottle** [comment]
# 第8章 控制注意力
## 你最强烈的感受（mandatary）

### 认知
1. 在信息时代，需要筛选信息，既不迷失在无关重要的细节里，也不错过微妙的重要线索。
2. 知识、信息、情景是不同的，知识是原始数据，知识揭示了信息的意义，情景是上下文。理解三者将帮助你更高效的管理思维，然而，注意力是前提。
3. 冥想训练可以提高人的注意力。就像训练肌肉一样：放松（放空，等待），练习。
4. 冥想的技巧：放松，注意自己的呼吸，意识到某些事情，但是不要有额外的思考，顺其自然。 在安静的地方、闭上眼睛、注意呼吸节奏、注意将思绪拉回呼吸上。
5. 认知尚未达到意识的水平。分清思维浸泡和拖延时间。

### 方法
1. 管理知识：使用外部信息处理系统，比如wiki
2. 优化情景：避免频繁的情景切换、多任务会降低性能：避免分心，单任务。
3. 管理干扰： 制定项目交流规划、放缓电子邮件、休息、保存情景堆栈（一旦意识到你将被打扰）
## 哪些适用于我们，怎么适用到我们的工作（mandatary）

## 好的句子

## 重要的概念（mandatary）
- 概念：注意力短缺
- 印象：注意力是供不应求的，事情很多，仅能关注一部分。
- 例子：老妇被人撞了一下，担心财物受损，注意力在检查财物上，并没有发现自己受伤。
- 出处：本书8.1章节

## 重要的人名（mandatary）
- 人名：保罗·格拉汉姆(Paul Graham)
- 印象：GTD方法的提出者
- 例子：一个海军飞行员在夜间以224km/h的速度在甲板上降落一架18T的飞机可能比一个普通少年切下一片硬面包片更安全。
- 出处：《黑客与画家：计算机时代的伟大想法》

- 人名：大卫·艾伦(David Allen)
- 印象：《黑客与画家》的作者
- 例子：无。
- 出处：《Getting Things Done》

## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：想做一件事总是说时间不够，并不是因为时间不够，而是注意力不够。
- 印象：准确的说是注意力的带宽不够，当你太忙时，你的注意力处于超载状态，所以会错过一些事情。
- 例子：你其实可以安排时间，让不同的时间段处理不同的事情，让你的注意力不至于超载。
- 出处：本书

- 反常识：创造力并不按考勤钟来运转，在压力下也一般不产生结果。
- 印象：必须有意识的忘掉问题，让问题在思维中浸泡一会儿。
- 例子：头一天想不出的问题，第二天可能就有了答案。
- 出处：个人经历。

**Comment by inkbottle** [comment]
# 第8章 控制注意力

## 你最强烈的感受（mandatary）

### 认知

1. 在信息时代，需要筛选信息，既不迷失在无关重要的细节里，也不错过微妙的重要线索。
2. 知识、信息、情景是不同的，知识是原始数据，知识揭示了信息的意义，情景是上下文。理解三者将帮助你更高效的管理思维，然而，注意力是前提。
3. 冥想训练可以提高人的注意力。就像训练肌肉一样：放松（放空，等待），练习。
4. 冥想的技巧：放松，注意自己的呼吸，意识到某些事情，但是不要有额外的思考，顺其自然。 在安静的地方、闭上眼睛、注意呼吸节奏、注意将思绪拉回呼吸上。
5. 认知尚未达到意识的水平。分清思维浸泡和拖延时间。

### 方法

1. 管理知识：使用外部信息处理系统，比如个人wiki
2. 优化情景：避免频繁的情景切换、多任务会降低性能：避免分心，单任务。
3. 管理干扰： 制定项目交流规划、放缓电子邮件、休息、保存情景堆栈（一旦意识到你将被打扰）

## 哪些适用于我们，怎么适用到我们的工作（mandatary）

1. 使用个人wiki（个人觉得笔记类工具其实不好，缺乏知识联系）
2. 单任务效率更高，避免情景切换。
3. 定时沟通而不是随时沟通。
等等...

## 重要的概念（mandatary）
- 概念：注意力短缺
- 印象：注意力是供不应求的，事情很多，仅能关注一部分。
- 例子：老妇被人撞了一下，担心财物受损，注意力在检查财物上，并没有发现自己受伤。
- 出处：本书8.1章节

## 重要的人名（mandatary）
- 人名：保罗·格拉汉姆(Paul Graham)
- 印象：《黑客与画家》的作者
- 例子：一个海军飞行员在夜间以224km/h的速度在甲板上降落一架18T的飞机可能比一个普通少年切下一片硬面包片更安全。
- 出处：《黑客与画家：计算机时代的伟大想法》




- 人名：大卫·艾伦(David Allen)
- 印象：GTD方法的提出者
- 例子：无。
- 出处：《Getting Things Done》

## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：想做一件事总是说时间不够，并不是因为时间不够，而是注意力不够。
- 印象：准确的说是注意力的带宽不够，当你太忙时，你的注意力处于超载状态，所以会错过一些事情。
- 例子：你其实可以安排时间，让不同的时间段处理不同的事情，让你的注意力不至于超载。
- 出处：本书

- 反常识：创造力并不按考勤钟来运转，在压力下也一般不产生结果。
- 印象：必须有意识的忘掉问题，让问题在思维中浸泡一会儿。
- 例子：头一天想不出的问题，第二天可能就有了答案。
- 出处：个人经历。

**Comment by Lemon312** [comment]
# 第九章 超越专家
## 你最强烈的感受（mandatary）
有效改变就是打破习惯，制定计划，立刻行动。
大脑很容易对习惯出现路径依赖，根深蒂固的老习惯不会消失，只能被持久的坚持击败。

改变总是比看起来要困难得多——这是一个事实，而不仅仅是忠告。根深蒂固的老习惯在大脑中形成了一条神经高速公路，而且不会主动消失。你可以在旁边建立新的神经高速公路，走不同的路线，抄近道，但是过去的高速公路仍然存在。它们总是在那里等你回来，重新依赖它们。实践可能不会十全十美，但是却可以保持长久。

请记住老习惯依然存在，如果你又回到了以前的某个习惯，不要太责怪自己。大脑就是这样工作的。只要承认失误即可，按照新的想法继续前进。当然老习惯肯定会再次发生，但是要意识到它的出现，并重新回到正确的道路上去。不论是要改变学习习惯，戒烟还是减肥，都是一样的道理

## 哪些适用于我们，怎么适用到我们的工作（mandatary）
改变，制定计划，行动。

## 好的句子
* 信念是真实的 （你的想法的确会改变大脑的机制和化学物质。必须相信改变是可能的。如果你认为自己会失败，你的预感就会实现）

## 重要的概念（mandatary）
- 概念：SMART 目标
- 印象：目标管理是使管理者的工作由被动变为主动的一个很好的管理手段，实施目标管理不仅是为了利于员工更加明确高效地工作，更是为了管理者将来对员工实施绩效考核提供了考核目标和考核标准，使考核更加科学化、规范化，更能保证考核的公正、公开与公平
        1. 绩效指标必须是具体的（Specific）
        2. 绩效指标必须是可以衡量的（Measurable）
        3. 绩效指标必须是可以达到的（Attainable）
        4. 绩效指标是要与其他目标具有一定的相关性(Relevant)
        5.绩效指标必须具有明确的截止期限（Time-bound）
无论是制定团队的工作目标还是员工的绩效目标都必须符合上述原则，五个原则缺一不可。
- 出处：9.2 明天上午做什么

## 重要的概念（mandatary）
- 概念：SQ3R
- 印象：SQ3R是英语Survey，Question，Read，Recite，Review五个词的第一个字母，分别代表“浏览、发问、阅读、复述、复习”五个学习阶段。
        1.紧扣文章中心
        2.有目的的读书
        3.读书的印象深刻
        4.大脑主动回忆
        5.记忆牢固
- 出处：9.2 明天上午做什么
## 重要的人名（mandatary）
- 人名：约翰 .菲尔波特.柯伦
- 印象：爱尔兰
- 例子：自由的代价是永远提高警惕 (例如开车)
- 出处：9.3 超越专家
## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：比专家更高的境界是什么？猜猜看
- 出处：9.3 超越专家

**Comment by ZLimin** [comment]
# 第7章 积累经验
## 你最强烈的感受（mandatary）

积累经验是学习和成长的关键，通过实践的方法学习，效果更好， 从实践中得到收获
真正的学习是来自实践和认知，而不是死记硬背或者外部的教学活动
用一种好玩的方式学习新资料或者解决问题，可以让这个过程变得更让人享受，也让学习变得更容易。

- 为了学习而玩耍

	“玩耍“：非目的性的探索， 不是仅仅接收信息，而是亲自探索和构建思维模型。
	 把玩问题并没有使问题变得容易，而是让我们看清如何了解这个问题。
	“玩耍”会引入一种新奇的感觉，也就是乐趣	

- 利用现有的知识

面对棘手问题时：
方法1：这个问题能否分成若干个更小的，更易于管理的部分，这种功能分解对软件开发人员非常有用，把事物分成大脑足以容纳的几部分。
方法2：想一想之前解决过的类似问题。
但寻找相似点也会有坏处，比如学习一剖新的编程语言，危险在于没有完成过渡和坚持混合的方式，当你没有完全接受新技能而处于过渡状态中时，新老方式被混合在一起。如果是彻底不同，你就必须放弃旧的方式（观念）

- 正确对待实践中的失败

例如在软件编程中，调试是不可避免的，调试意味着解决问题，而这些问题一般是我们自己制造的，而调试就是找出，改正问题，从错误中学习。
自由的探索才能学习，但你需要在你的安全的环境中探索，创造和应用，例如在公司之外尝试，在家里做开源项目，减少产生负面结果。

- 自由实验

能够原路返回稳定状态
重现任意时刻的工作产品
能够证实进展
了解内在诀窍
通过说教很难传授技能，通过探索可以学得更好
尝试培养非判断性的意识：不要想着来纠正，但是在出错时要知道，然后再采取行动纠正

观察，不做判断，然后行动

- 压力扼杀认知

当面对时间压力时，人最没有创造力
允许失败
想象超越感观
除了现实世界之外，也可以从大脑中取得经验
如果你周围全是高技能的人，你就会增长自己的技能水平，因为对他们实践和方法的观察与运用对于自己大脑的调节，使自己在更高水平上工作。
观察别人的行为，激励你也做同样的行为。

- 像专家一样学习

不断积累的经验会逐步改变你的观点，会发现自己从新知识的角度重新诠释过去的经验，并且增强了思维模型。

你有越来越多的模型来借鉴和应用，也有越来越多只可意会（直觉）的知识来帮你确定要搜索什么，以及何时搜索，你开始感受到专家行为的初级阶段。

## 哪些适用于我们，怎么适用到我们的工作（mandatary）
面对棘手问题时：
方法1：这个问题能否分成若干个更小的，更易于管理的部分，这种功能分解对软件开发人员非常有用：把事物分成大脑足以容纳的几部分。
方法2：想一想之前解决过的类似问题，也许相似点是完全一致的。
## 好的句子
在现实生活中，没有课程
为了更好的学习，请更好的玩
从相似点中学习，从差异中忘却
错误有益于我们，因为它们让 们思索到底发生了什么，知道什么地方错了，然后通过理解，纠正它。
让大脑为成功形成习惯
## 重要的概念（mandatary）
- 概念：时间压力宿醉
- 印象：面对时间压力时缺少创造力，而且这种压力还有一种后期影响。创造力会一直受到压制，持续到之后两天时间
- 例子：
- 出处：
## 重要的人名（mandatary）
- 人名：特丽萨阿马贝尔（Teresa Amabile）博士
- 印象：这个人的国籍，身份和其他重要信息
- 例子：面对时间压力时缺少创造力，而且这种压力还有一种后期影响：时间压力宿醉。创造力会一直受到压制，持续到之后两天时间
 - 出处：本书
## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：当面对时间压力时，人最没有创造力
- 印象：在多数人认为自己在面对最后期限时表现得非常有效率
- 例子：特丽萨阿马贝尔博士的压力宿醉论
- 出处：本书

**Comment by spicychicken** [comment]
# 第二章 从新手到专家的历程
## 你最强烈的感受（mandatary）
十年经验 或者 一年的经验重复九年
研究表明: 绝大部分人的大多数技能, 在他们大多数时间里, 从来没有高于第二阶段高级新手.
新手凭借规则, 专家凭借直觉工作.

## 哪些适用于我们，怎么适用到我们的工作（mandatary）
勇于承担责任.
在实践中保持技能.

## 重要的概念（mandatary）
- 概念：德雷福斯技能获取模型
- 印象：概括了从新手到专家必须经历的5个阶段.描述了能力,态度,素质和视角在不同的技术水平下是如何变化的

- 概念：新手
- 印象：很少或者根本没有经验, 非常在乎他们能否成功.

- 概念：高级新手
- 印象：能够多多少少的摆脱固定的规则, 能够独自尝试任务, 但仍难以解决问题. 想要快速获取信息而不打算寻根究底, 没有整体的思维, 也不打算有.

- 概念：胜任者
- 印象：开始寻求和运用专家的意见，并有效利用.  既可以指导新手，也不会经常骚扰专家. 能够建立问题域的整体概念模型.

- 概念：精通者
- 印象：全局思维, 纠正以为不好的工作表现并自我改进, 学习别人的经验, 有效的运用软件模式, 充分思考和反馈.

- 概念：专家
- 印象：各个领域内知识和信息的主要来源. 凭借直觉工作,而不需要理由. 知道哪些是无关紧要的细节, 哪些是非常重要的细节.

## 重要的人名（mandatary）
- 人名：Stuart Dreyfus & Hubert Dreyfus
- 印象：德雷福斯技能获取模型
- 出处：https://en.wikipedia.org/wiki/Hubert_Dreyfus  
https://en.wikipedia.org/wiki/Stuart_Dreyfus

## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识： 新手凭借规则, 专家凭借直觉工作.
- 印象：专家通常很难把他们的行为恰如其分的解释清楚, 他们的很多行为是如此的熟练以至是变成无意识的.
- 例子：老中医看病.

**Comment by windypu** [comment]
# 第4章 利用右脑

### 你最强烈的感受（mandatary）

我们容易忽略不寻常或者感觉不舒服的想法，而这恰恰是很糟糕的事情，你丢弃的可能是一生中最有价值的想法

### 笔记：
启动感官输入，使用感官输入可以使学生的学习效果提高五倍，例如使用各色的积木或玩具代替UML 图
关闭L，启动R 针线，绘画，音乐
醉酒写作酒醒修改：
    创作时候拥有自由的创造空间，不受常识或者实用的限制，你拥有充裕的时间尽情的发挥创造力或随后抛掉这些荒诞的东西，如果想法过早的受束缚，那么创造力就会被扼杀。如果你没有全局的概念就试图记忆细节，那么你会陷入僵局
    学习过程中不要迫于学会和记忆，首先只是要适应他，试着先理解它，掌握其主旨，然后采用传统的L型走入下一步
    训练两个脑半球，不仅仅有语言性的，符号性的，逻辑性的左脑，也包括空间性的，关系性的，综合性的右脑
结对编程 ：一种L型和R型协同工作的方式
    这种效果好的原因是，编程者锁定在语言模式下关注一定的细节，观察者则自由则自由的运用更多非语言性的区域
    当你与人交谈或者在白板或纸上和别人携手工作时，你的思维往往会变得更加抽象，你就可能发现新的抽象模式。
隐喻相通：L型和R型在隐喻上是相通的，即 创建类比上是相通的
    日常生活中我们经常使用隐喻 thread，mouse，window，folder ，语言学家 乔治 莱考夫 认为，如果没有隐喻，我们甚至不能思考。
系统隐喻：
    任何软件系统应该可以通过一种适当的隐喻来描述，例如一个薪酬系统可以比喻为一个邮箱系统，有分布的邮箱和交付时间。一个足够丰富的系统有助于指导系统的设计和解决开发过程中出现的问题，但是提出一个好的隐喻---能够帮助解决问题而不是产生更多问题可能是非常困难的，所以系统隐喻作为一种实践并未获得广泛应用。

讲个笑话吧：幽默产生于不同的想法之间创建新奇的联系，幽默就是建立在识别关系和扭曲关系的基础上的
    比如，我的一个电台播音员朋友每次在我开车经过一座大桥的时候就会消失
    我最好的朋友带着我的老婆跑了，我们想念他
    通过练习制造这些广泛的联系，你会更精于此，事实上你会改变大脑的结构来适应这种新活动。
利用图像流: 是一种用于收货R型意象的技术，其基本思路就是努力观察心里意象，并在心中回想一下。
利用自由日记：
    晨写技术--早晨的第一件事 让毫无防备的大脑倾倒想法,早上刚起床时，你还没有想象的那样清醒，潜意识仍然占据主角，你可以直接连通R型，至少一小会
    爱迪生有个有趣的习惯，他打盹时手里拿着一个装满滚珠的杯子，他知道当他逐渐入睡时，潜意识会接手他面临的问题并提供解决办法，当他熟睡时，滚珠会掉下来，撞击声会把他叫醒，然后他就记下脑子里面所有的事情。
    写博客，可以使用杰拉德 温伯格 的filedstone 方法
利用散步：伟大的想法或者领悟可能在最出乎意料的时候降临，可能在洗澡，刷碗，或者其他一些枯燥，琐碎的工作时，这是因为L型有点厌倦了这种常规任务走了神，让R型接手了
收获模式：
    
哪些适用于我们，怎么适用到我们的工作（mandatary）
首先利用类比方法解决关联性，理论性的问题，然后利用分析法来验证你的想法，最后回到R型以保持思维流畅，R型是源头，你要给他自由，无限的空间

### 重要的概念和人名（mandatary）

概念：罗扎诺夫教学法
印象：把学生放到漆黑的房间里放着音乐，做瑜伽，提高学生专注力和吸收新事物的能力，当学生进入状态后，用很多外语例子进行狂轰乱炸，没有说教，没有注解，没有解释。结果参见这种密集教学的学生比传统学生的表现更加出色
例子：罗扎诺夫教学法就是利用R型获取能力
出处：本书

概念：异类联想
印象：一个特殊的主题域形成一个参照系，从一个自完备的参照系到另一个不同的，意想不到的，不相容的参照系的突然切换是一个强大隐喻的基础，这两个体系的连接点成为异类联想。当异类联想时，两个参照系距离越远，关系越不可能，创造新的成果就越大。当两个参照系距离适中时我们会遇到一些格外具有创造性的隐喻 比如 二月春风似剪刀。 遥看瀑布挂前川等
例子：文学作品中使用了异类联想，我们工作中也同样使用
出处：the creative question

概念：伊莱亚斯 豪的奇遇
印象：1845年，伊莱亚斯 豪 尝试发明一种实用缝纫机，但是进展不是很顺利，有一天他做了一个非常可怕的噩梦，噩梦中他身处非洲，被饥饿的食人族绑架，他马上就要被扔进沸水里煮死，到那会猎人们却用一种非常可笑的长矛戳他。后来他通过描述这个可笑的长矛获得了灵感，获得了自动缝纫机的专利。
例子：R型不得不想办法来克服困难，伊莱亚斯 豪 的例子中通过可怕的记忆深处的怪梦来呈现
出处：本书

概念：杰拉德 温伯格的filedstone
印象：首先不需要计划手机特别的石头，只需要到处走一走，捡一些好看的石头堆起来备用，然后当你准备造墙的时候，就从石头堆里挑选匹配的石头放到正确的地方就可以了
例子：养成一种收集思维fieldstone的习惯，一旦有了积累，造墙就会变得很容易。
出处：本书
