### ISSUE TITLE
 软件开发者路线图

### ISSUE THREAD

**Issue by yxiaohui** [ReadingBooktogether/OneBookOneWeek#4]
# 本周任务
《软件开发者路线图》[https://book.douban.com/subject/4924164/](url)
任选一章，2016.2.6之前提交
这有一个链接，解释怎么在软件开发领域应用“刻意练习”
http://group.mtime.com/ALive/discussion/1431958/

#内容简介
作为一名软件开发者，你在奋力推进自己的职业生涯吗？面对今天日新月异和不断拓展的技术，取得成功需要的不仅仅是技术专长。为了增强专业性，你还需要一些软技能以及高效的学习技能。本书的全部内容都是关于如何修炼这些技能的。两位作者Dave Hoover和Adewale Oshineye给出了数十种行为模式，来帮你提高主要的技能。
本书中的模式凝结了多年的调查研究、无数次的访谈以及来自O’Reilly在线论坛的反馈，可以解决程序员、管理员和设计者每天都会面对的困难情形。本书介绍的不只是经济方面的成功，学徒模式还把软件开发看成一种自我实现的途径。读一读这本书吧，它会帮你充分利用好自己的生命和职业生涯。
厌倦了自己的工作？去找一个玩具项目来帮你重拾解决问题的乐趣吧，这叫“培养激情”。
感觉要被新知识淹没了？做点以前做过的事情，重新探索一下自己熟悉的领域，然后通过“以退为进”再次前进。
学习停滞了？那就去寻找一支由富有经验和才能的开发者组成的团队，暂时呆在里面“只求最差”。

# 作者简介 
Dave H. Hoover：Obtiva首席技师，喜欢在开发软件的同时培养软件开发者，他的专长是向企业家们交付项目。
Adewale Oshineye：软件工程师，从事过包括电子零售商销售网点系统、投资银行交易系统在内的各种大型项目开发。

## 提交格式：
尽量多做输出
每一个概念或者人名，请分别拷贝一份模板填写。
\# 第x章 xxx
\## 你最强烈的感受（mandatary）

\## 哪些适用于我们，怎么适用到我们的工作（mandatary）

\## 好的句子

\## 重要的概念（mandatary）
\- 概念：概念或者术语的名字
\- 印象：对概念或者术语的解释
\- 例子：对概念或者术语理解有帮助的例子
\- 出处：

\## 重要的人名（mandatary）
\- 人名：名字（英文名，方便查阅）
\- 印象：这个人的国籍，身份和其他重要信息
\- 例子：重要的观点，成就和著作
\- 出处：

\## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
\- 反常识：
\- 印象：
\- 例子：
\- 出处：

## 概念：
 - 概念： 心流（Flow）
 - 印象： 别名化境（Zone），亦有人翻译成神驰状态，是一种将个人精神力完全投注在某种活动上的感觉，心流产生时同时会有高度的兴奋与充实感。希斯赞特米哈伊认为，是心流发生的活动有一下特征
  1. 我们倾向去从事的活动
  2. 我们会专注一致的活动
  3. 有清楚目标的活动
  4. 有立即回馈的活动
  5. 我们对这个活动有主控感—挑战与技能之间达到平衡
  6. 在从事活动是我们的忧虑感消失
  7. 主管时间改变—例如可以从事很长的时间而不感觉时间的流逝
-	例子： 做一件自己喜欢的手工。
-	出处： [维基百科](https://zh.wikipedia.org/wiki/%E5%BF%83%E6%B5%81%E7%90%86%E8%AB%96)

**Comment by windypu** [comment]
# 第4章 准确的自我评估
## 你最强烈的感受（mandatary）
无论何时，无论你处于什么样的阶段，都要谦卑的做学徒。

## 哪些适用于我们，怎么适用到我们的工作（mandatary）
只求最差：
    问题：当你的学习速率曲线已经变平。
    解决办法是：找一个更强大的团队，在那里让自己成为最弱的成员，然后比其他人更用功。
    行动指南：列举你知道的所有团队，包括开源项目，其他部门，或其他公司的团队，按照技能水平排序，然后从中找一支对寻求上进的新人敞开大门的团队
 
找人指导：
    问题：当你意识到自己并不是第一个走上这条长路的人，你花了大量时间在探索死胡同
    解决方法：找那些走在你前头的人努力向他们学习，由于我们的领域非常年轻，公认的师傅非常少，因此更可能的情况是，你的学徒期被连续多为指导者监督，其技能的精通度各不相同。
    行动指南：挑一个拥有活跃邮件列表的工具，库或者社区。订阅这个列表，但开始不要发布任何消息，过段时间你将开始理解这个社区的价值，并了解哪些订阅者是耐心的老师，然后寻找这一列表中的人员，看他们是否愿意为你所学的功课提供一些非正式的建议。

同道中人
    问题：你的学徒期已经过了几个月或者几年，而开发组织的文化确让你失去的信心，你发现自己无人指导，束手无策。
    解决办法：你需要找一些像你一样希望自己优秀的人跟他们保持频繁联系
    行动指南：基于自己使用的工具，了解的语言，一起共事的人，度过的博客，以及让你受过启发的思想，列举下所有可能加入的社区。确认那些可能在你的领域搞线下的实际聚会，逐一参加这些聚会。或者自己创建一场这样的聚会。随着组织的壮大，你拥有一个由不定期参加聚会的成员组成的核心小组。如果你的用户组变得足够大。足够有活力，即使你不在的时候也会维持下来。这时你就可以说自己拥有一个社区了。
    
密切交往：
   问题：尽管你拥有定期见面的指导者和同道中人，但当回到软件开发的时候你任然是独自一人。你的生产率进入稳定状态，学习停滞了，你感觉有更高级的技术和方法而自己抓不住。
   解决办法：找机会和另外一个软件开发者坐在一起，肩并肩完成一项实际动手的任务。总有一些细微的技艺，只有跟一个同事近距离合作才能学到。这些技艺通常被认为太琐碎，没有人会在教别人的时候提到他，但他们的影响却可以累加起来。
   行动指南：找来一个你所认识的，对启动或者加入开源项目有浓厚兴趣的人，每周安排一个晚上，跟他一起做这个项目。忙碌的生活压力可能会你们合作背后的动力。如果出现这种情况，你必须适应它，设法保证项目一直往前走。

打扫地面：
    问题：你是项目里的新学徒，你不确定自己在团队中的位置，团队也不确定你的水平。
    解决办法：主动完成简单又无趣但是又必须完成的任务
    行动指南：被你的团队拖延了几个月的最邋遢的任务是什么？它应该是所有人都抱怨，确没有人愿意解决的那个，你去解决它。看自己能否找到一种超出人们预期的并为自己带来快乐的方式，创造性的解决这个问题。

## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：宁为狮尾，不为狐头
- 印象：你必须去追求那些技艺精湛，学徒甚至无法想象其水平的其他团队，组织，熟练工和师傅，向他们学习，以此来抗争趋平庸的倾向。
- 例子：只求最差 与鼓励人们尽快获得更高职位的常规文化相悖。
- 出处：本书

**Comment by inkbottle** [comment]
# 第2章 空杯心态

## 你最强烈的感受（mandatary）
学习是一种比所有其他技能更强大的技能。 例子：《X战警：最后一战》

## 哪些适用于我们，怎么适用到我们的工作（mandatary）

学徒、技师、专家之间的区别：学徒是没有技能、专家仅有自己专业方面的知识，固步自封、技师是不断成长的。

### 白色腰带

要先放下已有的知识，固有的认识可能会阻碍你认识新的事物。 一个例子： 以一个新手的角色进入团队，帮助并和团队合作，将有利于融入、提升团队。帮助团队解决问题时，合作找出的办法总是更切实可行的。

回到新手状态会很痛苦。学习新的知识期间，生产率还会降低。

### 释放激情
释放激情是有风险的， 如果团队士气较低，或者团队比较不欢迎新人，你可能在背后遭人白眼。因为这些人认为：竞争力比学习能力重要得多，这会使你留下不好的印象。
在合适的团队中释放激情将会有独特的好处：作为新手，自由的想象力等会增加团队的智慧，并带来多样性。

### 暴露无知
不去问问题，不习惯学习这种过程的人，最终成了“专家”。习惯学习的过程带来的不适，也是一种能力。
专家很重要，这也是必然的，但这不是学徒的目标。

### 正视无知
适当的暴露无知。过多会让人觉得自己能力过低，过少则不利于在新领域的成长。
把更大的团队利益置于个人利益之上，不要因为个人的学习妨碍了项目的进度与健康。

### 深水区域
勤勉的实践自己的技能，可以达到更高的水准；安于平淡无奇的技能，最终会退化成碌碌无为。
承担艰巨的任务并做一些让人紧张的事情才会让人成长。需要意识到，这有风险，如果估算失误，项目需要的能力超出了自身的极限，就像水位高过头顶。然而仍然需要从失败中做好准备，从失败中振作将打开新的大门。

当水位高过头顶，方法可以参考：高人指点/同道中人。

### 以退为进
1. 暂时退回自己的能力范围之内会会获得镇定。
2. 区分以退为进和向失败投降。
3. 专长的回馈是直接而切实的，但这样做的风险不会立即显现，直到某一天你采取的任何措施都以为时已晚。说明你的专长已经不再适用了。这时候重新学习比持续的学习要来得痛苦得多。
4. 回顾有助于认识事情的某些情形，获得不同的方法。


## 重要的概念（mandatary）
- 概念：空杯心态
- 印象：时刻清空自己学会的知识，不受思维定式的影响，以新人的状态学习。
- 例子：无
- 出处：本章

## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识： You must unlearn what you have learned
- 印象：不是东西懂得越多越好吗？为什么学习某些东西之前要忘掉已有的经验呢？因为已有的经验是思维定式的结果，这些会影响对新事物的全面认知。
- 例子：如果你是一个C程序员，那么你的思维会被工具禁锢，你将在短时间内无法全面理解面向对象的程序是如何组织和工作的。
- 出处：《Star War II: The Empire Strikes Back.》

**Comment by stone-monkey** [comment]
# 第3章 走过漫漫长路
## 你最强烈的感受（mandatary）
- 技重于艺: 可用于美学之间抉择,首先满足基本功能.技师至少不会挨饿
- 持续动力: 让自己的编程能力持续走下去. 比如在Java上是专家, 还可以拓展自己的工具集(Ruby....).
- 培养激情: 采取措施来保护自己对软件技艺的激情. 选择自己的议题, 排除负面影响. 从自己从事的工作中找到喜欢的事情.
- 自定路线: 自定长期路线, 不断重新评估自己的路线. 即使离开当前的公司也保持自己的路线. 例子: Chris McMahon为了成为专注开发, 保持持续学习, 放弃当前公司.
- 使用头衔: 不要让头衔影响你, 它只是一种娱乐. 影响深刻的头衔和责任不表明学徒期已结束, 而是我们行业中技师还很缺乏. 
- 坚守阵地: 大多数人把提升到管理职位等同于成功. "每一个不写程序的日子, 你都是在远离熟练工的目标". 应该让自己坚守在记忆精通的道路上, 不要让自己提升到远离技艺的职位上. 
- 另辟蹊径: 在"漫漫长路"上走了一些时候, 可能觉得这条路不适合自己. 可以换一条, 但意味着和技艺的"漫漫长路"说再见, 永远或者暂时. 

## 哪些适用于我们，怎么适用到我们的工作（mandatary）
参见上一段
## 好的句子

## 重要的概念（mandatary）
- 概念：死亡行军 -- 巴丹死亡行军
- 印象：巴丹死亡行军是第二次世界大战中著名的战争罪行与虐待俘虏事件，与新加坡大屠杀、南京大屠杀并称为日本在二战期间的远东三大暴行。
- 例子：美菲联军投降后，投降人数约有78,000人，包括67名女护士，这78,000人成为日军的战俘后，开始遭日军强索财物，并开始押解到约120公里外的战俘营，路程以徒步行军为主，但整个行军过程除了初期给予少许的食物外（根据幸存者表示，仅给一次高尔夫球大小的饭团），一路上不再提供给战俘食物，是因美军投降时早已用尽食物，而日军因未料到美军过早投降，所以也没有事先准备供给战俘的食物。经常有找寻饮水与食物者被日军以刺刀杀死或开枪处决，同时也驱赶与阻止当地的菲律宾人给予战俘食物与水，一路上因怕战俘逃跑，而只准他们从路边水洼中饮水，即便有若干侥幸者躲过日军眼线而偷喝到几口河水，也因河水已严重遭受污染（河中漂浮着尸体以及绿色泡沫），且气温达摄氏38度，最后引发严重的腹泻与呕吐而死，后来日军在也终于追加设置了几个食物供应点。
如此经过不吃不喝的强行军，最后虽抵达目标营地，但沿路上因饥渴而死（最初即是因饥饿和粮食不继才选择投降）及遭日军刺死、枪杀者达15,000人之多。而抵达战俘营后并非摆脱了死亡威胁，由于日军也在营地内虐待战俘，包括拷打折磨、斩首杀害、逼迫苦力劳务、刻意挨饿等，如此在抵达营地的两个月内又死去了约26,000人。
- 出处：维基百科

## 重要的人名（mandatary）
- 人名：
- 印象：
- 例子：
- 出处：

## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：
- 印象：
- 例子：
- 出处：

**Comment by spicychicken** [comment]
# 第五章 恒久学习
## 你最强烈的感受（mandatary）
不从历史中学习的人注定重复历史
## 哪些适用于我们，怎么适用到我们的工作（mandatary）
### 提高带宽
在学习某个新的技能时, 如何高效的获取和理解新知识?
* 订阅软件开发方面的blog
* twitter上follow软件大师
* 订阅流量较高的在线邮件列表, 重现别人遇到的问题并尝试回答
* 加入对某种新技术比较兴奋的本地用你组
* 说服老板送你去参加技术大会等...
* 读完一本书后, 写邮件和作者联系一下, 表达下谢意, 问一点问题.
理解何时提高带宽: 虽然能加速你的学习, 但是也会降低你的开发速度. 不要迷失在信息的海洋中...

### 不断实践
学习到的新技能一般都是在工作中实践, 这也是我们会在工作中犯错误的原因.
在日常的编码活动中, 很少有机会通过犯错来学习
路数[Kata]()是在没有对手的情况下练习,强调的是流畅性,力量,速度和控制力.
武馆[Dojo]()一个人民可以定期聚会并公开练习编码"路数"的地方.[CodinGame](https://www.codingame.com/)

### 质脆玩具
来自失败的经验与来自成功的经验同样多.
不断实践的一种方式, 侧重于提供一个安全的地方来犯错误.
> 维护一个个人wiki, 不断在其上试验各种新奇技术.  
每学习一门新语言, 就用它编一个游戏.

### 使用源码
如果没有一个好的实践范本拿来研究并效仿, "不断实践"模式只会让保护那些你都不知道自己已经养成的坏习惯.
> 对编程能力最精细的测试就是给程序员大约30页的代码, 看他能多快地通读并理解它. ---Bill Gates [Programmers At Work]()  

好处: 
* 学会特定语言社区中的各种惯用法和精妙细节
* 从别人的错误中学习知识的机会

### 且行且思
> 自我反省是困难的, 但我相信我们能从失败中学到的东西比从成功中学到的更多.---Norm Kerth, [Project Retrospective]()  

Pair Working和TDD的结合: 一名开发者写一个测试, 然后把键盘推给他的搭档, 他的搭档写代码让这个测试通过, 然后立即写出下一个测试, 再把键盘推回第一个家伙, 如此反复.
> 无论我们发现了什么, 考虑到当时的已知情况, 个人的技术水平和能力,可用的资源,以及手上的状况, 我们理解并坚信: 每个人对自己的工作都已全力以赴. ---[The Retrospective Prime Directive](http://www.retrospectives.com/pages/retroPrimeDirective.html)

### 记录所学
你也不应该低估写作本身的威力......不从历史中学习的人注定重复历史.

### 分享所学
技艺不精的人常常不知道自己技艺不精.

### 学会失败
失败是不可避免的, 它迟早会发生在每个人身上.

## 重要的人名（mandatary）
- 人名：Norm Kerth
- 印象：Project Retrospectives: A Handbook for Team Reviews作者
- 例子：Project Retrospectives: A Handbook for Team Reviews
- 出处：https://www.safaribooksonline.com/library/view/project-retrospectives-a/9780133488753/

## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：
- 印象：
- 例子：
- 出处：

**Comment by ZLimin** [comment]
# 第6章 安排你的课程
## 你最强烈的感受（mandatary）
离开学校后，我们要成为不断学习过程中的主动参与者，并且成长为一名可以挥舞强大的工具来组织并收集信息的开发者。学会享受学习的过程，这会让你受益匪浅。
在信息充足的时候，我们获取知识的途径有很多，我们要安排自己的学习时间去学习阅读，靠自己去寻求建议，安排自己的课程。

## 哪些适用于我们，怎么适用到我们的工作（mandatary）

阅读列表
用它来跟踪你打算阅读的书，并记下已经读过的书，可以把这个列表放在公共空间，这样能让他人从你学到的东西中受益。最好这个阅读列表可以排序，并能区分哪本书是你何时读过的。
任何一本书，能从中获得的最有价值的东西就是一列值得阅读的其它书目。我们可以把书中的参考书目列出来，并进行排列。这个你就可以把引用最多的书目找出来。这些书也是值得优先阅读的。

坚持阅读
即使你精通了“入门语言”， 但更需要继续深入的学习。更多的概念在不断的出现，这就需要我们不断的学习阅读。

尤其是在我们计算机领域发展迅速，我们更应该坚持阅读学习，与计算科学发展的前沿保持联系，拓宽你的思路。

任何时候都应该随身带一本书，利用每天的空余时间来学习

钻研名著
“暴露无知“， 向别人请教那些自己不知道的概念，以及它们出自何书，并将这些书加入你的阅读列表
成功的学徒常常关注经久不衰的书，然后通过上网和实验来学习这些知识如何演化。但关注于经典作品也有风险：对它们投入过多的精力，而完全不顾那些能提高日常技能的,更加注重实效的知识和信息。在你的阅读列表中，要确保经典名著和现代的，更注重实效的书和文章混合出现。

深入挖掘
学会深入挖掘一些工具，技术和技艺。对知识的学习要达到知其所以然的程度。深度意味着要理解导致一种设计的推动力，而不仅仅是设计细节。

深入挖掘技术，可以使我们对自己构建的系统，你可以真正解释其内部机制。

不要简单的记住别人说过的一句话，这句话可能是从一本书的引用的。要真正理解任何思想，你都需要重建它第一次被表达的上下文，这样，你就可以理清其中保留下来的思想的精髓。

阅读教程的时候，不要去寻找可以复制的代码，而是去寻找可以放置新知识的思想结构。如果具备这种更深入的知识，当遇到问题时，你会比原来的教程走的更远。

如果只拥有表面知识，你会永远意识不到自己正尝试解决的问题要么已经有了众所周知的解决方案，要么根本是不可能的。

常用工具

## 好的句子
即使每两个月读一本编程相关的好书，也就是每周35页左右，用不了多久，你就会对我们的行业有深入的理解，并使自己不同于周围的人。

找到自己专业或兴趣领域中的优秀作品---所有最好的书籍，文章或演讲，然后孜孜不倦的钻研这些作品。

在实践中，算法问题不会在大项目刚开始的时候就出现，然后，当突然之间程序员不知道如何继续下去或者目前的程序显然不恰当时，它们就作为子问题出现了。

## 重要的人名（mandatary）
- 人名：名字（英文名，方便查阅）
- 印象：这个人的国籍，身份和其他重要信息
- 例子：重要的观点，成就和著作
- 出处：
## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：
- 印象：
- 例子：
- 出处：

**Comment by Ironman-Jason** [comment]
第1章 绪论
你最强烈的感受（mandatary）

任何职业都会经历3个阶段：学徒，熟练工，大师。
从来没有好好思考过这3个阶段是什么。从绪论的思考中，看到一个从业者的职业操守和行业责任感。

哪些适用于我们，怎么适用到我们的工作（mandatary）

工作几年后是否遗失了学徒期的热情？------在新知识面前放下你的身段，暴露你的愚蠢，向新领域上的熟练工，大师学习，这样是快速成长的好途径。
为什么选择这个职业？你的职业发展是你预期的吗？酷？改变世界？更多的收入？好玩？-------不忘初心，方得始终。 

好的句子

1. 成长型思维模式：如果你愿意钻研一件事，你就能做得更好，一切也将得以改善。
2. 基于你从周围世界获得的反馈，始终不断适应并作出改变的要求。
3. 一种对注重实效而非教条主义的向往，肯于牺牲理论上的纯洁性和未来的完美而达到“今天把事情做完”的意愿。
4. 一种认为分享知识胜过隐藏独享的信念。
5. 一种敢于试验并愿被证明失败的意愿。
6. 内控倾向：更愿意掌控自己的命运并为之负责，而非等待别人给我们答案。
7. 一种对于个体而非群体的关注：我们追寻的是自身的改变，而非世界的改变。这不是一场“领导者-追随者”式的运动。
8. 包容性：一个有用的系统应该能够从软件开发社区的所有元素中识别并吸收那些最好的思想。
9. 以技能为中心，而非以过程为中心。拥有高超技能比使用正确的过程重要。
10. 情景学习：最好的学习方法，就是同那些使用你要学习的技能来达到某种目标的人处于同一个房间。

重要的人名（mandatary）

人名：名字（英文名，方便查阅）
情景学习（situated learning）:Etienne Wenger, Swiss, educational theorist and practitioner.
《Software Craftsmanship》: Pete McBreen,

**Comment by Lemon312** [comment]
# 第6章 安排你的课程
## 你最强烈的感受（mandatary）
要善于挖掘知识中的知识，就是不断的深入知识中的细节，这样就能对知识有更清晰、更透彻的认识。
以至于更深层次的：为什么会形成这种知识或概念。

## 哪些适用于我们，怎么适用到我们的工作（mandatary）
阅读列表
维护一张“阅读列表”，用它来跟踪你打算阅读的书，并记下已经读过的书。
由于阅读列表实际上是个优先级队列，最终你会发现有的书已经在队列中下沉得太深，你可能永远也不会再读它们了。
开始时挑一本宽泛的书，让自己对目标主题有大致的了解；然后选择一些内容具体的书，从而掌握该主题中自己感兴趣的方面。比起乱读一通自己还没有相关经验的书，或者乱读一通自己尚不具备相关预备知识的书，在合适的时间读合适的书会有更好的效果

坚持阅读
重视你对学习的如饥似渴，消化掉尽可能多的文字。
利用每天空余时间来学习。

钻研名著
暴露无知，向别人请教那些自己不知道的概念，以及它们出自何书。将这些书加入你的“阅读列表”。
名著能指引正确的方向。
也不能只关注名著，而完全不顾那些能提高日常技能的、更加注重实效的知识和信息。在阅读列表中，要确保经典名著和现代的、更注重实效的图书和文章混合出现。

深入挖掘
学会深入挖掘一些工具、技术和技艺。对知识的学习要达到“知其所以然”的程度。深度意味着要理解导致一种设计的推动力，而不仅仅是设计的细节
从第一手资料中获取信息，找出是谁第一次提出了那种思想，弄明白他们当初想要解决的问题。这样的上下文通常在思想四处传播的过程中由于各种转译而丢失了。
如果只拥有表面知识，另一种可能的后果是：你会永远意识不到自己正尝试解决的问题要么已经有了众所周知的解决方案，要么根本是不可能的

常用工具
找出一组常用的工具并关注它们。最好这些工具都是你不再需要阅读文档的。有了这些工具知识，你就能对工作中的特定部分提供可靠的时间估算，从而将风险限制在新的、未探索过的领域上。
可用于完成工作的最佳工具并不是你最熟悉的工具。在学徒期使用的工具到你变成熟练工时肯定会变得过时。最终，你所钟爱的所有工具都将变成垃圾。为了职业生涯的成功，你必须学会从容地获取或放弃一些熟练工具
