### ISSUE TITLE
知识创造的螺旋

### ISSUE THREAD

**Issue by yxiaohui** [ReadingBooktogether/OneBookOneWeek#5]
# 本周任务
《知识创造的螺旋》
[https://book.douban.com/subject/1734687/](url)
2.24之前提交。

#内容简介
与工业社会不同，知识社会的生产手段不再是机器，而是人的头脑和双手。知识由两个对立的部分“形式知识”和“暗默知识”构成，本书主旨在于，新的知识是通过一个协调及超越对立双方的“综合”辩证过程，在连续的动态的“场”中创造出来的。在知识一经创造出来就变得过时的时代，我们惟有整合各种对立因素，才能够在不断创造新知识的过程中，用知识称雄未来。所以，扼杀矛盾是最大的误区，重要的是要辩证地对待矛盾、拥抱矛盾、综合矛盾。
享有世界”知识运动之父”美誉的野中郁次郎和竹内弘高教授大胆尝试，从知识视角对管理学进行反思，以IBM，佳能，索尼、本田等十几个世界知名企业的实例，讲述知识创造的螺旋上升过程。

# 作者简介
竹内弘高，一桥大学国际企业战略学院教授、院长，在一桥大学就职前，曾在哈佛商学院任教，曾与迈克尔·波特合著《日本还有竞争力吗》(Can Japan Compete?)一书。曾获加州大学伯克利分校Haas商学院的MBA和博士学位。. 野中郁次郎，一桥大学国际企业战略学院教授，在知识管理领域，野中教授足被引述最多的作者。他与竹内合著过《创造知识的企业》(The Knowledge-cmating Company)。1996年，该书荣获美国出版学会“年度最佳管理类图书”大奖，该著作也是被引用最多的知识管理类专著。

# 提交格式：
尽量多做输出
每一个概念或者人名，请分别拷贝一份模板填写。
\# 第x章 xxx
\## 你最强烈的感受（mandatary）

\## 哪些适用于我们，怎么适用到我们的工作（mandatary）

\## 好的句子

\## 重要的概念（mandatary）
\- 概念：概念或者术语的名字
\- 印象：对概念或者术语的解释
\- 例子：对概念或者术语理解有帮助的例子
\- 出处：

\## 重要的人名（mandatary）
\- 人名：名字（英文名，方便查阅）
\- 印象：这个人的国籍，身份和其他重要信息
\- 例子：重要的观点，成就和著作
\- 出处：

\## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
\- 反常识：
\- 印象：
\- 例子：
\- 出处：

## 概念：
 - 概念： 心流（Flow）
 - 印象： 别名化境（Zone），亦有人翻译成神驰状态，是一种将个人精神力完全投注在某种活动上的感觉，心流产生时同时会有高度的兴奋与充实感。希斯赞特米哈伊认为，是心流发生的活动有一下特征
  1. 我们倾向去从事的活动
  2. 我们会专注一致的活动
  3. 有清楚目标的活动
  4. 有立即回馈的活动
  5. 我们对这个活动有主控感—挑战与技能之间达到平衡
  6. 在从事活动是我们的忧虑感消失
  7. 主管时间改变—例如可以从事很长的时间而不感觉时间的流逝
-	例子： 做一件自己喜欢的手工。
-	出处： [维基百科](https://zh.wikipedia.org/wiki/%E5%BF%83%E6%B5%81%E7%90%86%E8%AB%96)

**Comment by stone-monkey** [comment]
# 第二章 创造知识的企业
## 笔记
- 西方的管理传统一脉相承,根深蒂固----组织即"处理信息"(效率, 成本, 投资回报率等)的机器.
- 日本的例子: "汽车进化论"口号,创造了Honda City, 个人复印机和啤酒罐的类比,让佳能成功转向办公室自动化领域.
-- 日本管理方式的核心, 不仅仅"处理"客观的信息,而且还发掘每个员工的暗默的,常常是高度自治的洞察力,直觉及预感,并对这些能力进行检验,然后为公司所利用.
-- 日本企业对知识有比较全面的思考方式. 企业不是机器, 而是一个有有生命的有机体.
- 新的知识总是源于个体.创造知识的企业的重要活动是使个人知识为他人所用.
- "明示的"知识: 属于形式和系统的知识. 产品规格, 科学公式等...
- "暗默的"知识: 属于一种不容易被表达清楚的知识.比如大阪的那位面包大师的那种非正规, 且难以讲清楚的技能.
- 四种创造知识的基本模式
- 1. 从暗默知识到暗默知识(共同化): 如学徒学师傅的手艺. 学徒和师傅都没有获得系统的见识, 所以不可能方便整个组织利用
- 2. 从形式知识到形式知识(联结化): 比如财务主管收集总结一份财务报告. 但这种并没有扩展该公司现有的知识基础.
- 3. 从暗默知识到形式知识(表现化): 比如财务主管根据多年经验, 编制出一种控制预算的方法.
- 4. 从形式知识到暗默知识(内在化): 形式知识在组织内共享, 有利于其他人拓宽, 延伸以及重新构造自己的暗默知识.
- 从比喻到模型: Honda设计"高小子"汽车过程中, 提出了"一起冒险吧", "汽车进化论", "人最大化, 机器最小化"等口号
- "比喻"(把矛盾的事物及想法联系到一起."汽车进化论"中的汽车机械和进化论有机体联系在一起) --> "类比"(化解矛盾. 啤酒罐解决个人复印机的墨盒, 找出相识指出, 低廉的制造方式) --> "模型"(创新的知识为组织其他人所用, 如提出各种规格, 定义)
- 组织的基本原则可以归结于"冗余". 是创造知识的第一步. 如重叠的产品开发, 引入"内部竞争原则", 从不同视觉来审视某个项目.
- 总裁们喜欢阐述企业的"概念伞"来解释他们的角色. "概念伞"是指, 用高度概括和抽象的词言表达某些宏观概念, 他们代表将表面分立的活动或者业务连接成密不可分的整体的共同特性. 


## 你最强烈的感受（mandatary）
## 哪些适用于我们，怎么适用到我们的工作（mandatary）
- "冗余"也可以用于小组内部. 比如对某一问题找解决方案的时候, 可以让一两个人同时进行, 从不同的方面,根据不同的经验寻找不同的解决方案,在最终决定使用哪一个.

## 好的句子
- 创造新知识就意味着在个体与组织不断自我更新的过程,向企业及其每个员工注入新鲜的活力.
- 比喻是一种独特的认知方式, 它是处于不同的情景, 具有不同经历的个体, 借助想象力和象征手法, 在不需要分析和概括的情况下, 通过直觉来了解某件事物的方式. 
- 一个较为模糊的愿景可以使员工和工作小组获得制定目标的自由空间和自主权.
- 人们步调不一致的时,会发生争吵,因此很难将他们聚拢在一起. 可是, 如果一个小组从一开始便步调一致的话, 要想取得良好的效果也很困难.
- 中层管理者将一线员工与高层主管的暗默知识进行了综合, 是暗默知识得以明晰化, 并且将其融会在新技术和新产品中. 从这个意义上讲, 他们才是"创造知识的企业"中名副其实的"知识工程师".

## 重要的概念
- 概念："明示的"知识
- 印象：属于形式和系统的范畴. 产品规格, 科学公式等...我们可以容易地交流并分享这类知识
- 例子：科学公式, 投资收益比等
- 出处：本书

- 概念："暗默的"知识
- 印象：是高度个人化的知识.由于它难以转变成形式知识, 所以不容易传达给其他人.
- 例子：烤面包师傅的技艺
- 出处：本书

## 重要的人名
- 人名：迈克尔.波拉尼(Michael Polanyi)
- 印象：哲学家:"我们所知道的东西比能说出来的要多"
- 例子：迈克·波拉尼(Michael Polanyi, 1891年3月11日 – 1976年2月22日) 是匈牙利和英国的一位通才。他对物理化学、经济和哲学都有很重要的贡献。他认为实证主义给人提供了一种“知”的错觉，会使人无法达到最高成就。
- 出处：维基百科

- 人名：马克斯.布莱克(Max Black)
- 印象：是隐喻现代研究的奠基者,"相互作用理论"的开创者.同时他还是一个专业的分析哲学家, 曾被认为"代表了分析哲学的最高发展"
- 例子：
- 出处：

## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：
- 印象：
- 例子：
- 出处：

**Comment by inkbottle** [comment]
# 第3章 组织的创造知识理论

## 你最强烈的感受（mandatary）

组织无法创造知识，个体的暗默知识是组织知识的基础。


### 知识转换的四种模式


- 共同化
从暗默知识到暗默知识

- 联结化
从形式知识到形式知识

- 内在化
从形式只是到暗默知识

- 表出化
从暗默知识到形式知识

### 促进知识螺旋的条件

- 意图： 推进个体知识的产生
- 自主管理：	推进知识的转换
- 创造性混沌： 激发活力，在安逸的环境下，个人几乎不可能进行深刻的思考。
- 冗余： 有关业务活动，管理职责和整个企业方面的信息有意图的重叠。
- 必要多样性法则



### 组织创造过程的五个阶段
1. 分享暗默知识
2. 创造概念
3. 验证概念
4. 建造原型
5. 转移知识

## 哪些适用于我们，怎么适用到我们的工作（mandatary）

整个过程都适用，从过程1到5，将会完成个人知识到团队知识和技能的双向转换。


## 好的句子

## 重要的概念（mandatary）
- 概念：知识螺旋
- 印象：组织调动个体创造和积累的暗默知识，通过知识转换的四种模式“在组织层次上”得以放大，并且在存在论维度较高的层级（小组&组织）上固定下来。这个过程叫做“知识螺旋”。
- 例子：大公司都这样做。
- 出处：本书

## 重要的人名（mandatary）
- 人名：奈瑟（Neisser）
- 印象：认为，在有目的的活动背景下，“认识”和“理解”的过程才能进行。
- 例子：NA
- 出处：本书注释

## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：组织也能有自己的知识和技能
- 印象：一直认为只有个人的经验和技能需要创建和经营。
- 例子：由个人组成的组织其实在宏观上也表现出与其他组织或团体不同的特质。比如：当一个公司的高管集体出走，媒体将会对该公司前景表现出担忧。
- 出处：本书概念。

**Comment by spicychicken** [comment]
# 战略形成过程与对话
> 单音性: 由一种视角所支配的交流, 如宗教等  
多音性: 由多种视角所主导的沟通

## 战略形成过程
### 有意图的战略:  
* 具有组织意图, 由可以确认的决策者所设计出来的战略. 是有意识选择的结果, 通常是理性的, 属于分析类型的, 以文档或口头语言形式,明确的, 正式的记录在案.
* 缺点: 该战略也许不是基于现实情况之上, 或者战略本身非常出色但组织也许无法对其进行实施  
* 满足一定条件时, 该类型战略才有可能实施:
>1. 组织成员必须充分领会有意图的战略   
>2. 在第一线的管理者必须了解有意图战略的内含
>3. 实现这一战略不能被技术,市场或外部政治因素所阻碍

### 突现战略:  
* 在没有组织意图或集中决策情况下所发生的行动模式.
* 缺点: 不一定能够获得对整个组织有利的战略


有意图的战略适合进入初期和成熟阶段, 而突现战略更适合发展阶段.

### 对比:
有意图的战略 | 突现战略 | 说明
----|------|----
集中|分散|
统一视角|多元视角|
原有含意|新含意|突现战略是组织的所有成员在原有战略概念中发现新含意的过程,而有意图的则试图共享原有含意
分析|创意|有意图的战略侧重分析, 而突现可能产生某些从未预料到的创新思想
先分析,后行动|先行动,后学习|
合理化|冗余|突现战略缺乏集中协调和控制,可能导致冗余和失败.而有意图的可能更具合理性,和更有效率
确定|不确定|突现战略形成过程适合于充满不确定性因素的环境
战略概念|局部行动|突现战略是从局部行动中涌现出来的,但有意图的战略更多是由战略概念驱动的
权威性|参与性|单音性对权威性方式给有效, 而多音性则对参与性方式更有利
层级体制|扁平结构|

## 你最强烈的感受（mandatary）
拥抱矛盾, 而不是避开矛盾.

## 哪些适用于我们，怎么适用到我们的工作（mandatary）
采用突现战略形成过程, 多进行多音性的对话.

**Comment by ZLimin** [comment]
# 第四章 创造知识作为一个综合的过程
知识以及创造和利用知识的能力被认为是企业可持续竞争力的最重要来源。理解创造知识过程的关键在于熟悉超越及综合这些矛盾体的辩证思维与行为。 综合不是妥协，相反，它是通过动态的对话与实践过程对对立特性的培养。

企业竞争制胜的关键是速度和效率。
但海格尔和辛格指出企业不能同时既追求规模与范围经济，以指望速度经济这样彼些矛盾的原则。企业和个体的能力是不能改变的，而且战略的作用是发现矛盾特性之间的最佳点。
企业和个体是创造知识的实体，可以通过发现新解决方案来综合矛盾特性的成长实体。我们可以通过知识创造过程来追求综合经济，不断提高自身极限，而不仅仅在既有制约条件下寻找最佳点。

知识创造是一个超越的过程，在这个过程中，创造知识的实体通过获得新知识对旧的边界进行超越，从而进入新的自我。在这个过程中，新和概念和有利于互动的结构被创造出来，为创造知识的实体进行新的创造知识循环过程提供可能性能限制条件。

知识创造是一个组织与组织内部的个体和组织周围环境产生相互作用从而对不断涌现的矛盾进行超越的综合过程。
## 组织即“处理信息的机器”与组织即“创造知识的实体”
由于人类的理性有限，应对复杂的现实必须由组织来完成。现实被分解成若干较小且简单到足以为个体所处理的片断信息，然后，组织成员分别对这些信息进行处理，再将它们重新结合到一起，这样，整个组织最终便可对应对复杂的现实。
例如：汽车制造

因此对，组织来说，主要的课题是怎样将整个过程分解成较小的任务或模块，以及如何协调人最终完成。

这种组织的相互作用过程中，除了解决问题外，组织还要创造和明确表述问题，开发和运用知识来解决问题，从而在解决问题的行动中创造新的知识，组织和个人也在此过程中成长。
在知识创造的过程中，应当与具有不同角度的人进行交流，从而理解现实/问题的全貌。
例如：丰田公司要求员工将对各自的任务的观察和交流当作整个汽车制造过程中的一部分，并且要示他们分享各自的工作知识以便对整个过程进行完善。

将组织视为创造知识的实体，可以将这些矛盾看成为创造知识的必备之物而不是障碍，知识是通过对矛盾的综合创造出来的，而不是在矛盾之间发现某种最佳平衡。

## 知识创造和战略和作用
组织与环境矛盾的战略作用
定位学派： 定位学派专注组织运营环境， 倾向于强调对环境的分析，但忽略了组织的内部过程。
以资源为基础的观点： 侧重审视企业内部所拥有的资源， 拥有优秀资源的企业才会获得收益。

知识是通过综合组织内部的资源与环境之间的矛盾创造出来的，战略可以被描述为内部资源与环境调整相结合。 因此，应该两者兼顾。知识是组织与环境之间互动创造出来的。

# 知识创造是一个综合的过程
如何对环境和内部资源进行综合：
知识创造是通过人类与环境的互动来实现的。 我们是环境的一部分，环境也是我们的一部分，周围的资源和机遇塑造了我们的日常行动，而我们的行动最终也会创造新的社会现实。

**实践意识**：是指人们并没有进行真正思考的认知层面，人们知道的比可以表达出来的东西要多。
**推证意识**：使人们让行动合理化，它可以被认为是认知的意识阶段。
**暗默知识**：指与特定情境相关的个人知识，难于进行形式化，也难于进行交流。
 **形式知识**： 明示或系统化的知识，是那些由形式，系统的语言表达，可以进行传递的知识。

暗默知识与实践意识有相似之处，形式知识则类似于推证意识。

知识创造始于共同化过程; 暗默知识主要通过共享知识的方式获得。
例如：传统的学徒制，学徒工是通过切身体验获得一门手艺所需的暗默知识。

暗默知识通过表出化过程被表述为形式知识，得以明示化的暗默知识便可以与他人进行分享，成为经概念，形象和书面文件形式出现的新知识的基。

组织所创造和分享的形式知识又可以通过内在化过程被转化为暗默知识，这个过程可以理解为实践。所以，形式知识必须通过行动，实践和反思才能得以活用，并真正成为个人知识的一部分。

例如：培训帮助人员了解自己是环境的一部分，通过阅读有关工作和组织文件，通过对资料的反思，丰富他们的暗默知识的基础。

让这四种知识转换模式的运动，形成一种螺旋而不是循环。在知识创造的螺旋中，暗默知识与形式知识之间的互动通过知识转换的四种模式被放大，增强。

## “场”：创造知识的地方
创造知识的过程也一定是以情境为转移的，知识创造需要一个场所，在这个场所里信息通过解读被赋予含意，然后转变为知识。

“场”定义为分享，创造及运用知识的动态的共有情境。为进行个别知识转换过程及知识螺旋运动提供能量，质量及场所。

每个场所分别提供一个基地，以利于进行某一特定阶段的知识转化程序，并使知识之创造加速进展。将四个场所的四个知识转化程序前后加以连贯起来，就构成一系列不断自我超越的程序，同时也随之显现 了知识转化的螺旋式演进情况

例如：日本7-11公司

# 重要的概念（mandatary）
SECI模形： 知识转化的四种模式：共同化（Socialization）、表出化 (Externalization)、联合化(Combination)和内在化（Internalization)

"场"： 每个场所分别提供一个基地，以利于进行某一特定阶段的知识转化程序，并使知识之创造加速进展。将四个场所的四个知识转化程序前后加以连贯起来，就构成一系列不断自我超越的程序，同时也随之显现 了知识转化的螺旋式演进情况（from 百度百科）

**Comment by Lemon312** [comment]
# 第八章 跨组织的知识创造---知识与网络
## 你最强烈的感受（mandatary）
丰田公司及其关联供应商集团是在一个稳定、紧密联系企业网络内进行知识创造的典型代表。人员互调也在其他不同层次上进行。丰田公司向许多供应商派遣高级主管，在供应商那里，他们充当高级运营主管等。退休的丰田主管通常会接受丰田公司附属企业的管理职位。
硅谷模型中。知识是通过企业间以及大学和研究机构之间广泛而流动的各个环节创造出来的。

## 哪些适用于我们，怎么适用到我们的工作（mandatary）
比如可以和ASWU组互相调动。

## 重要的概念（mandatary）
- 概念：SECI模型
- 印象：在企业创新活动的过程中隐性知识和显性知识二者之间互相作用、互相转化，知识转化的过程实际上就是知识创造的过程。知识转化有四种基本模式——潜移默化(Socialization)、外部明示 (Externalization)、汇总组合(Combination)和内部升华 (Internalization)，即著名的SECI模型


- 概念：暗默知识
- 印象：暗默知识源自个人的亲身体验，是与个人信念、视角及价值观等精神层面密切相关。我们常说的经验、直觉、秘诀、预感等都属于暗默知识的范畴。是指一种凭主观和直觉本质所获得的，难于以任何系统化或逻辑的方式进行处理或传输科学认知、原则或技术原理。
