### ISSUE TITLE
【W10】《生命的心流》

### ISSUE THREAD

**Issue by yxiaohui** [ReadingBooktogether/OneBookOneWeek#6]
# 本周任务
《生命的心流》
https://book.douban.com/subject/3424068/

3.10之前提交。

#内容简介
《生命的心流》主要内容：2300年前，古希腊哲人狄奥根尼打着灯笼也找不到一个诚实的人；而今，要找到一个真正快乐的人，恐怕更加困难。在一个高度物化的社会里，对财富、地位、权力的追逐。未必能使人更加快乐。唯有从每天的生活经验、当下的体验品质即“心流”中创造乐趣。才能提升身心的品质。掌控心灵意志，达致心流体验的瞬间，你将撬动生命的力量之源。

# 作者简介
米哈里·契克森米哈赖，芝加哥大学心理系教授。著有畅销书《幸福的真意》、《自我演化》、《创造力》等。前美国心理协会会长马丁·瑟利斯曼誉之为“积极心理学的世界级领导人物。”

# 提交格式：
尽量多做输出
每一个概念或者人名，请分别拷贝一份模板填写。
\# 第x章 xxx
\## 你最强烈的感受（mandatary）

\## 哪些适用于我们，怎么适用到我们的工作（mandatary）

\## 好的句子

\## 重要的概念（mandatary）
\- 概念：概念或者术语的名字
\- 印象：对概念或者术语的解释
\- 例子：对概念或者术语理解有帮助的例子
\- 出处：

\## 重要的人名（mandatary）
\- 人名：名字（英文名，方便查阅）
\- 印象：这个人的国籍，身份和其他重要信息
\- 例子：重要的观点，成就和著作
\- 出处：

\## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
\- 反常识：
\- 印象：
\- 例子：
\- 出处：

## 概念：
 - 概念： 心流（Flow）
 - 印象： 别名化境（Zone），亦有人翻译成神驰状态，是一种将个人精神力完全投注在某种活动上的感觉，心流产生时同时会有高度的兴奋与充实感。希斯赞特米哈伊认为，是心流发生的活动有一下特征
  1. 我们倾向去从事的活动
  2. 我们会专注一致的活动
  3. 有清楚目标的活动
  4. 有立即回馈的活动
  5. 我们对这个活动有主控感—挑战与技能之间达到平衡
  6. 在从事活动是我们的忧虑感消失
  7. 主管时间改变—例如可以从事很长的时间而不感觉时间的流逝
-	例子： 做一件自己喜欢的手工。
-	出处： [维基百科](https://zh.wikipedia.org/wiki/%E5%BF%83%E6%B5%81%E7%90%86%E8%AB%96)

**Comment by inkbottle** [comment]
# 第 1 章 日常生活的构成

## 你最强烈的感受（mandatary）

### 何谓美好人生
活得充实圆满，充分利用时间与潜能，发挥个人特质，与宇宙万物契合相融。
追寻声明意义的唯一途径就是以现有的能力，慢慢理清历史真相及未来的可能性。

### 如何活得更好
为求尽善尽美，应当先了解现实生活中的需求及潜在挫折。

### 体验生活的方式
休憩、生产、消费及互动的循环

个人生活绝大部分取决于性别、年龄及社会地位。

### 个体差异
环境、个体特征。
个人生活绝大部分取决于性别、年龄及社会地位。

### 我们如何运用时间
时间，最终会成为我们的稀有资源。

### 生产类活动
"挣钱"大约占个体1/4 - 1/2的时间。

### 维持类活动
维持身体机能、居住环境要素：
饮食、打扫、整理仪容

### 休闲类活动
闲暇时间。爱好，打发时间。最有效的是学习。最耗精神的是看电视。

### 三类社交形态

1. 陌生人、工作伙伴、同学： 这片公共区域对个人潜力开发极为重要，风险最大，成长幅度最高。
2. 家人： 责任感、独一无二的经验感受。
3. 孤独、无人相伴： 相当一部分时候是独自一人状态。

### 经验取样法

## 哪些适用于我们，怎么适用到我们的工作（mandatary）

对社交形态的阐释，工作的区域成长幅度在三类社交形态中是最高的。


## 好的句子
- 追寻声明意义的唯一途径就是以现有的能力，慢慢理清历史真相及未来的可能性。
- 个人生活绝大部分取决于性别、年龄及社会地位。

## 哪些观点跟你原来的理解不一样（反常识）（mandatary）
- 反常识：追寻声明意义的唯一途径就是以现有的能力，慢慢理清历史真相及未来的可能性。
- 印象： 认识当下就好。
- 例子： 以史可以为鉴。
- 出处： 本书。

**Comment by windypu** [comment]
# 第5章 休闲的利弊
## 你最强烈的感受（mandatary）


## 哪些适用于我们，怎么适用到我们的工作（mandatary）
### 防止意识混乱
大多数人若无目标可追寻，无朋友可互动，注意力和动机就会开始消散，人往往就会开始钻牛角尖，想些无解的问题，徒增自己的焦虑。为了避免这种情形当事人会采取若干摆脱精神紊乱的策略，比如看电视，读小说，赌博，酗酒，吸毒。这些方法能带来短暂的振奋，但事后只残存一丝安然惆怅之感。

闲暇时光繁荣的社会经常有一些仪式，舞蹈，竞赛，咖啡屋，啤酒屋等，这些方法可以防止意识混乱，但是对体验品质的提升没有多大助益。

如果空闲时间无所事事，人的精神混乱度将会大为提升，整个人只感觉懒懒散散，兴趣全无。
### 主动式休闲与被动式休闲
![default](https://cloud.githubusercontent.com/assets/19277676/23738361/84303960-04d3-11e7-8aaf-a5a850090758.png)
每一项心流活动都需要开始的时候花些心思准备然后才能享受到乐趣，如果你十分疲惫，焦虑或缺乏纪律，无法克服起步的障碍，就只能转换方向，改做一些虽然不乐趣但是能力可及的事。
被动休闲-找朋友聊天，阅读一些不花脑筋的书，或是打开电视机，并不需要花费太多的精力，也不需要技巧，所以很多青少年和成年人都喜欢。

费神，困难的心流容易带来焦虑，而被动式休闲确不会。
所以放松并不是坏事，重点在于分量，如果被动式休闲活动当做填补空闲的主要或唯一策略必然会出问题，一旦养成习惯整个生活品质会大受影响。

### 在娱乐中寻找心流
有些人深感工作乏味   ，将所有的生产责任抛开，比如工程师辞职在餐馆洗一个冬天的碗只为赚取一夏的攀岩费用。
很多冲浪爱好者仅仅过着够糊口的日子
###善用休闲时光
想要让闲暇时光得到妥善的运用，就得付出工作般的努力和才智，主动休闲有利于成长，但过程确不轻松。在科学和艺术在变成专业之前，绝大多数的科学研究，诗歌，绘画和乐曲创作都是在闲暇时间完成的。

## 好的句子

对众多美国人而言，休闲是有害的
一般人认为休闲无需动用任何技能，人人皆可为之，但有证据显示，事实恰恰相反。休闲并不比工作更快乐，拥有自由的时间也不见得能够提升生活品质。除非当事人知道怎样有效的利用空闲时间，但这份能力绝不与生俱来的。
## 重要的概念（mandatary）
- 概念：周日精神病
- 印象：退休常导致慢性忧郁症。周日碰巧一个人又无事可做的人容易得这个病
- 例子：心里分析师费伦次注意到他的病人在周日爆发歇斯底里症和忧郁症的概率远高于其他日子，这种症状取名叫 “周日精神病”
- 出处：本书

**Comment by Oogway1983** [comment]
第9章 爱你的命运
## 你最强烈的感受（mandatary）

1 人最大的障碍是自己；
2 减少自己的需求；
3 设定目标（比实现自我更伟大、更永恒的目标）--感觉是指精神上的更多一点


##句子
如果我们只对自己负责，事情会简单得多，不幸的是，往往事与愿违。人们若想享有美好的生活，就必须积极负起全人类、全世界的责任。------好累。

**Comment by ZLimin** [comment]
# 第二章 心流何时有
心流隐含的意义，就是许多我形容自己表现最杰出时那份水到渠成，不费吹灰之力的感觉，也就是运动家所谓的处于巅峰。艺术家及音乐家所说的灵思泉涌。
## 快乐何来
人类的所作所为都是为了追求快乐。我们追求快乐并不是因为它能够给我们带来其它的好处，而是因为快乐本身就是目的。

## 快乐是主观感受
物质生活与快乐之间有联系
一般人会认为，生活在物质环境好，政治稳定的国家的人会比其它国家的人更快乐，但这并不是绝对的。
人们自述的快乐与其自身物质有关。积极，乐观，坚强的人比较可能感觉到快乐。
生活质量不仅仅取决于快乐，也包含我们追求快乐所做的事。如果一个人不能设定生存目标，不能充分运用心智，他所获得的美好感受，不过只是人类潜能的一小部分。没有梦想，没有风险，生活也就变得微不足道。

## 意图与目标
在我们决定将心思投入到特定工作中时，就是兴起一股意图，替自己设定一个目标。

不论行动是出于自己内在动机还是外在动机，都比漫无目的的行动要好。

你会被塑造成为什么样的人，最终还是受你所追求的目标所左右，一个人若缺乏目标，就会三心二意，难以贯彻始终。

目标也决定了一个人的自尊。
自尊心的强弱取决于期望与成功的比例。自尊心弱是由于目标设的太高，或成功太少。

## 意识的内容
要提升心智运作的层次，你就必须学会集中注意力。

## 智力与注意力
要使先天的才能转变成充分发展的智力， 你就必须学会控制注意力。

## 心流体验

## 重要的概念（mandatary）
- 概念：精神能趋疲（psychic entropy）
- 印象: 忧伤，恐惧，焦虑或无聊等负面情绪，会产生“精神能趋疲”, 导致我们无法集中精神处理外在事物，也无法恢复内在主观情绪的常态
- 例子：对概念或者术语理解有帮助的例子
- 出处：
- 概念：精神反能趋疲（psychic negentropy）
- 印象: 快乐，力量或机敏等正面情绪则是” 精神反能趋疲“
- 例子：对概念或者术语理解有帮助的例子
- 出处：
